[tox]
envlist = lint, type, py311, py312, py313, py314
isolated_build = true
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest --cov=src --cov-report=term-missing {posargs}

[testenv:lint]
deps = flake8
skip_install = true
commands = flake8 src/ tests/

[testenv:type]
deps =
    mypy
    pytest
commands = mypy src/
