"""HCL translation engine and exception auditor behavior."""

import json
import logging
from pathlib import Path

import pytest

from meraki2tf.alerts import AlertDispatcher, AlertEvent, EventType, Notifier
from meraki2tf.hcl_generator import ADDRESS_LEDGER_FILENAME, HclImportGenerator
from meraki2tf.models import (
    UNREADABLE_MARKER,
    FeatureConfiguration,
    MerakiDevice,
    MerakiNetwork,
    NetworkGraph,
)
from meraki2tf.openapi_parser import OpenApiParser
from meraki2tf.provider_catalog import ProviderCatalog
from conftest import fixture_catalog


class RecordingNotifier(Notifier):
    channel = "recording"

    def __init__(self) -> None:
        self.events: list[AlertEvent] = []

    def send(self, event: AlertEvent) -> None:
        self.events.append(event)


@pytest.fixture()
def recorder() -> RecordingNotifier:
    return RecordingNotifier()


@pytest.fixture()
def generator(
    spec_parser: OpenApiParser, recorder: RecordingNotifier
) -> HclImportGenerator:
    return HclImportGenerator(
        spec_parser, AlertDispatcher([recorder]), fixture_catalog
    )


def _network(network_id: str = "N_1") -> MerakiNetwork:
    return MerakiNetwork.from_payload({"id": network_id, "organizationId": "org-123"})


def _graph(**overrides: tuple) -> NetworkGraph:  # type: ignore[type-arg]
    values = {
        "networks": (_network(),),
        "devices": (
            MerakiDevice.from_payload({"serial": "Q2AB-CDEF-GHIJ", "networkId": "N_1"}),
        ),
        "features": (
            FeatureConfiguration(
                "/networks/{networkId}/appliance/vlans/{vlanId}", ("N_1", "10")
            ),
        ),
    }
    values.update(overrides)
    return NetworkGraph(organization_id="org-123", **values)


def test_unreadable_endpoint_is_audited_never_imported(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """An asset discovery could not read has no payload to rebuild from
    and its provider Read would fail identically during import — it must
    land in the coverage manifest as unsupported, not in imports.tf."""
    reason = "HTTP 500 from the Meraki API after every retry"
    report = generator.generate(
        _graph(
            features=(
                FeatureConfiguration(
                    "/networks/{networkId}/appliance/vlans",
                    ("N_1",),
                    {UNREADABLE_MARKER: reason},
                ),
            )
        ),
        tmp_path,
    )
    (gap,) = report.unsupported
    assert reason in gap.reason
    assert "could not be read" in gap.reason
    assert gap.identifiers == ("N_1",)
    content = report.imports_file.read_text(encoding="utf-8")
    assert "vlans" not in content
    assert any(
        event.event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED
        for event in recorder.events
    )
    # The mapped resource type is exempt from deletion detection this
    # run: its objects are absent because the read failed, not because
    # they left Meraki.
    assert report.unreadable_types == frozenset({"meraki_appliance_vlan"})


def test_suppressed_addresses_keep_capture_but_lose_import_blocks(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """A regeneration pass must not write import blocks back for
    resources the plan loop already dropped as unexpressible — but they
    stay captured so coverage/deletion accounting is unchanged."""
    baseline = generator.generate(_graph(), tmp_path)
    (target,) = [
        asset.address
        for asset in baseline.captured
        if asset.address.startswith("meraki_appliance_vlan")
    ]
    report = generator.generate(
        _graph(), tmp_path, suppress_addresses=frozenset({target})
    )
    assert report.imports_written == baseline.imports_written - 1
    assert target in {asset.address for asset in report.captured}
    content = report.imports_file.read_text(encoding="utf-8")
    assert target not in content


def test_generates_import_blocks_for_all_mapped_assets(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    report = generator.generate(_graph(), tmp_path)
    content = report.imports_file.read_text(encoding="utf-8")

    assert report.imports_written == 3
    assert report.unsupported == ()
    assert recorder.events == []
    assert "to = meraki_network.n_1\n" in content
    # meraki_network's identity demands the (always-known) org ID too.
    assert 'id = "org-123,N_1"' in content
    assert "to = meraki_device.q2ab_cdef_ghij\n" in content
    assert "to = meraki_appliance_vlan.n_1_10\n" in content
    assert 'id = "N_1,10"' in content
    assert content.startswith("# Generated by meraki2tf")


def test_unmapped_asset_triggers_exception_audit(
    generator: HclImportGenerator,
    tmp_path: Path,
    recorder: RecordingNotifier,
    caplog: pytest.LogCaptureFixture,
) -> None:
    graph = _graph(
        features=(
            FeatureConfiguration("/networks/{networkId}/unknownFeature", ("N_1",)),
        )
    )
    with caplog.at_level(logging.ERROR, logger="meraki2tf.hcl_generator"):
        report = generator.generate(graph, tmp_path)

    assert report.imports_written == 2  # network + device still written
    assert len(report.unsupported) == 1
    flagged = report.unsupported[0]
    assert flagged.api_path == "/networks/{networkId}/unknownFeature"
    assert "No Terraform resource maps" in flagged.reason
    assert any("UNSUPPORTED FEATURE" in record.message for record in caplog.records)

    assert len(recorder.events) == 1
    event = recorder.events[0]
    assert event.event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED
    assert event.details["identifiers"] == ["N_1"]


def test_id_component_arity_mismatch_is_flagged(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    graph = _graph(
        features=(
            FeatureConfiguration(
                "/networks/{networkId}/appliance/vlans/{vlanId}", ("N_1",)
            ),
        )
    )
    report = generator.generate(graph, tmp_path)
    assert len(report.unsupported) == 1
    assert "2 ID component(s)" in report.unsupported[0].reason
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED


def test_assets_already_in_state_are_skipped(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """Consecutive runs aggregate only the delta into existing state."""
    report = generator.generate(
        _graph(),
        tmp_path,
        existing_addresses=frozenset(
            {"meraki_network.n_1", "meraki_device.q2ab_cdef_ghij"}
        ),
    )
    content = report.imports_file.read_text(encoding="utf-8")

    assert report.skipped_existing == 2
    assert report.imports_written == 1  # only the VLAN is new
    assert "meraki_network.n_1" not in content
    assert "meraki_device.q2ab_cdef_ghij" not in content
    assert "to = meraki_appliance_vlan.n_1_10\n" in content
    assert recorder.events == []  # skipping is not an exception-audit event


def test_duplicate_assets_are_written_once(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    report = generator.generate(
        _graph(networks=(_network(), _network()), devices=(), features=()), tmp_path
    )
    assert report.imports_written == 1


def test_label_collisions_are_disambiguated_not_dropped(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """Distinct IDs that sanitize to the same label must all be captured."""
    report = generator.generate(
        _graph(
            networks=(_network("N-1"), _network("N.1"), _network("N_1")),
            devices=(),
            features=(),
        ),
        tmp_path,
    )
    content = report.imports_file.read_text(encoding="utf-8")

    assert report.imports_written == 3
    assert "to = meraki_network.n_1\n" in content
    assert "to = meraki_network.n_1_2\n" in content
    assert "to = meraki_network.n_1_3\n" in content
    assert 'id = "org-123,N-1"' in content
    assert 'id = "org-123,N.1"' in content
    assert 'id = "org-123,N_1"' in content


def test_collision_suffixes_stay_stable_against_existing_state(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """A colliding asset tracked under its suffixed address stays skipped."""
    graph = _graph(
        networks=(_network("N-1"), _network("N.1")), devices=(), features=()
    )
    report = generator.generate(
        graph,
        tmp_path,
        existing_addresses=frozenset({"meraki_network.n_1"}),
    )
    content = report.imports_file.read_text(encoding="utf-8")

    # N-1 (first) resolves to n_1 = already tracked; N.1 keeps n_1_2.
    assert report.skipped_existing == 1
    assert report.imports_written == 1
    assert "to = meraki_network.n_1_2\n" in content
    assert 'id = "org-123,N.1"' in content


def test_labels_are_sanitized_to_valid_terraform_identifiers(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    report = generator.generate(
        _graph(networks=(_network("123-A.B"),), devices=(), features=()), tmp_path
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert "to = meraki_network.r_123_a_b\n" in content
    assert 'id = "org-123,123-A.B"' in content


def test_folded_alias_path_is_flagged_not_misimported(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """/organizations/{organizationId}/networks folds into meraki_networks
    with matching arity — importing an org ID as a network must be refused."""
    graph = _graph(
        networks=(),
        devices=(),
        features=(
            FeatureConfiguration(
                "/organizations/{organizationId}/networks", ("org-123",)
            ),
        ),
    )
    report = generator.generate(graph, tmp_path)

    assert report.imports_written == 0
    assert len(report.unsupported) == 1
    assert "organization_id" in report.unsupported[0].reason
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED
    content = report.imports_file.read_text(encoding="utf-8")
    assert "org-123" not in content  # no wrong import block was emitted


def test_import_ids_are_hcl_escaped(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """IDs from arbitrary dump JSON must not break or inject into HCL."""
    report = generator.generate(
        _graph(networks=(_network('N"1${evil}'),), devices=(), features=()),
        tmp_path,
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 1
    assert 'id = "org-123,N\\"1$${evil}"' in content
    assert '"N"1' not in content  # no unterminated string literal


def test_control_char_in_import_id_is_flagged_not_imported(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """F3: a control character (here a newline) in an ID only ever comes
    from a corrupted/doctored dump — no live object carries it, so the
    escaped import block could never address anything. It must surface as
    an unsupported coverage gap, never a wrong-but-covered import."""
    report = generator.generate(
        _graph(networks=(_network("N\n1"),), devices=(), features=()), tmp_path
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 0
    (gap,) = report.unsupported
    assert "control character" in gap.reason
    assert "import {" not in content  # no import block emitted at all
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED


def test_surrogate_in_import_id_is_flagged_not_mutated(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """F3: a lone UTF-16 surrogate cannot be UTF-8 encoded; the escaper
    would silently swap it for ``?`` and emit an import ID that addresses
    a different (or no) object while coverage calls the asset covered.
    Reject it as unsupported instead."""
    report = generator.generate(
        _graph(networks=(_network("L_\ud800123"),), devices=(), features=()),
        tmp_path,
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 0
    (gap,) = report.unsupported
    assert "un-encodable" in gap.reason
    assert "?" not in content  # the mutated ID was never written
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED


def test_trailing_whitespace_id_is_flagged_not_silently_trimmed(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """F3: the model layer no longer strips edge whitespace from an ID,
    so a trailing-newline network ID surfaces as unsupported rather than
    being trimmed into a wrong-but-covered import."""
    report = generator.generate(
        _graph(networks=(_network("L_123\n"),), devices=(), features=()), tmp_path
    )
    assert report.imports_written == 0
    (gap,) = report.unsupported
    assert "whitespace" in gap.reason


def test_normal_ids_are_unaffected_by_the_identifier_guard(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """The guard must reject only silently-altered IDs — an ordinary
    network ID still imports unchanged."""
    report = generator.generate(
        _graph(networks=(_network("L_647392837465"),), devices=(), features=()),
        tmp_path,
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 1
    assert report.unsupported == ()
    assert 'id = "org-123,L_647392837465"' in content


def test_empty_id_component_is_flagged_not_imported(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """F4: a feature whose path values include an empty component emits
    ``id = "net,"`` — an ID that can never import — yet used to be counted
    pending. An empty NETWORK id already aborts cleanly; an empty path
    component must be flagged unsupported the same way, not covered."""
    report = generator.generate(
        _graph(
            networks=(),
            devices=(),
            features=(
                FeatureConfiguration(
                    "/networks/{networkId}/appliance/vlans/{vlanId}", ("N_1", "")
                ),
            ),
        ),
        tmp_path,
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 0
    (gap,) = report.unsupported
    assert "empty" in gap.reason
    assert '"N_1,"' not in content  # no un-importable block emitted
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED


def test_identifier_guard_preserves_coverage_accounting(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """Every discovered graph object must still reconcile as pending,
    unsupported, or duplicate — a rejected ID moves the object from
    pending to unsupported, it does not drop from the totals."""
    graph = _graph(
        networks=(_network("N_ok"), _network("N_bad\n")),
        devices=(),
        features=(),
    )
    report = generator.generate(graph, tmp_path)
    graph_candidates = len(graph.networks) + len(graph.devices) + len(graph.features)
    graph_unsupported = len(report.unsupported) - report.spec_gap_count
    assert graph_candidates == (
        len(report.captured) + graph_unsupported + len(report.duplicates)
    )
    assert report.imports_written == 1  # only N_ok
    assert graph_unsupported == 1  # only N_bad


def test_collision_suffixes_ignore_discovery_order(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """API listing order changes between runs must not reshuffle which
    colliding asset owns the base label vs the suffixed one."""
    ordered = generator.generate(
        _graph(networks=(_network("N-1"), _network("N.1")), devices=(), features=()),
        tmp_path,
    ).imports_file.read_text(encoding="utf-8")
    reordered = generator.generate(
        _graph(networks=(_network("N.1"), _network("N-1")), devices=(), features=()),
        tmp_path,
    ).imports_file.read_text(encoding="utf-8")
    assert ordered == reordered


def _ledger(tmp_path: Path) -> dict:  # type: ignore[type-arg]
    return json.loads(
        (tmp_path / ADDRESS_LEDGER_FILENAME).read_text(encoding="utf-8")
    )["addresses"]


def test_new_colliding_id_never_steals_a_state_tracked_address(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """An asset's identity is its import ID, not its ordinal position
    among colliding labels: a new colliding ID appearing between runs
    must not shift state-tracked addresses (address churn on a tracked
    resource proposes destroys), must not be faked as already_in_state
    (coverage may never claim an unimported asset is imported), and
    must not re-import an already-tracked object at a second address."""
    first = generator.generate(
        _graph(networks=(_network("N-1"), _network("N.1")), devices=(), features=()),
        tmp_path,
    )
    assert _ledger(tmp_path) == {
        "meraki_network.n_1": "org-123,N-1",
        "meraki_network.n_1_2": "org-123,N.1",
    }

    # "N;1" sorts before both existing IDs — pre-ledger ordinal
    # assignment would hand it the state-tracked n_1 address.
    second = generator.generate(
        _graph(
            networks=(_network("N-1"), _network("N.1"), _network("N;1")),
            devices=(),
            features=(),
        ),
        tmp_path,
        existing_addresses=first.captured_addresses,
    )
    by_id = {asset.import_id: asset for asset in second.captured}
    assert by_id["org-123,N-1"].address == "meraki_network.n_1"
    assert by_id["org-123,N-1"].already_in_state is True
    assert by_id["org-123,N.1"].address == "meraki_network.n_1_2"
    assert by_id["org-123,N.1"].already_in_state is True
    assert by_id["org-123,N;1"].address == "meraki_network.n_1_3"
    assert by_id["org-123,N;1"].already_in_state is False
    content = second.imports_file.read_text(encoding="utf-8")
    assert second.imports_written == 1
    assert "to = meraki_network.n_1_3\n" in content
    assert 'id = "org-123,N;1"' in content


def test_deleted_asset_slot_stays_reserved_while_state_tracks_it(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """A colliding newcomer must not inherit a deleted object's address
    while its state entry awaits deletion review — the dead address must
    stay absent from captured so the deletion alert still fires."""
    first = generator.generate(
        _graph(networks=(_network("N-1"), _network("N.1")), devices=(), features=()),
        tmp_path,
    )
    # "N-1" left Meraki (state still tracks it); "N;1" is new.
    second = generator.generate(
        _graph(networks=(_network("N.1"), _network("N;1")), devices=(), features=()),
        tmp_path,
        existing_addresses=first.captured_addresses,
    )
    by_id = {asset.import_id: asset for asset in second.captured}
    assert by_id["org-123,N.1"].address == "meraki_network.n_1_2"
    assert by_id["org-123,N;1"].address == "meraki_network.n_1_3"
    assert by_id["org-123,N;1"].already_in_state is False
    assert "meraki_network.n_1" not in second.captured_addresses
    # The dead slot stays reserved in the ledger while state has it.
    assert _ledger(tmp_path)["meraki_network.n_1"] == "org-123,N-1"


def test_ledger_prunes_addresses_confirmed_out_of_state(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """Once a deletion is confirmed out of state, its ledger entry goes
    too — the ledger never grows beyond the state it protects."""
    generator.generate(
        _graph(networks=(_network("N-1"), _network("N.1")), devices=(), features=()),
        tmp_path,
    )
    generator.generate(
        _graph(networks=(_network("N.1"),), devices=(), features=()),
        tmp_path,
        existing_addresses=frozenset({"meraki_network.n_1_2"}),
    )
    assert _ledger(tmp_path) == {"meraki_network.n_1_2": "org-123,N.1"}


@pytest.mark.parametrize(
    "content",
    ["{not json", json.dumps(["not", "an", "object"]), json.dumps({"addresses": 7})],
)
def test_unreadable_ledger_degrades_to_ordinal_assignment(
    generator: HclImportGenerator, tmp_path: Path, content: str
) -> None:
    """A corrupt sidecar ledger must never fail the DR run — collision
    handling degrades to the deterministic ordinal behavior."""
    (tmp_path / ADDRESS_LEDGER_FILENAME).write_text(content, encoding="utf-8")
    report = generator.generate(
        _graph(networks=(_network("N-1"), _network("N.1")), devices=(), features=()),
        tmp_path,
    )
    assert {asset.address for asset in report.captured} == {
        "meraki_network.n_1",
        "meraki_network.n_1_2",
    }
    # The rewritten ledger is healthy again.
    assert _ledger(tmp_path) == {
        "meraki_network.n_1": "org-123,N-1",
        "meraki_network.n_1_2": "org-123,N.1",
    }


def test_ledger_entries_without_string_ids_are_ignored(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    (tmp_path / ADDRESS_LEDGER_FILENAME).write_text(
        json.dumps(
            {
                "addresses": {
                    "meraki_network.n_1": 7,
                    "meraki_network.n_1_2": "org-123,N.1",
                }
            }
        ),
        encoding="utf-8",
    )
    report = generator.generate(
        _graph(networks=(_network("N-1"), _network("N.1")), devices=(), features=()),
        tmp_path,
    )
    by_id = {asset.import_id: asset for asset in report.captured}
    # The malformed pin is dropped; the healthy one still holds.
    assert by_id["org-123,N.1"].address == "meraki_network.n_1_2"
    assert by_id["org-123,N-1"].address == "meraki_network.n_1"


def test_stale_ledger_pin_with_changed_label_is_ignored(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """A pin from a renamed resource type (or changed label derivation)
    must not resurrect the old address for a fresh asset."""
    (tmp_path / ADDRESS_LEDGER_FILENAME).write_text(
        json.dumps({"addresses": {"meraki_legacy_network.n_1": "org-123,N-1"}}),
        encoding="utf-8",
    )
    report = generator.generate(
        _graph(networks=(_network("N-1"),), devices=(), features=()), tmp_path
    )
    (asset,) = report.captured
    assert asset.address == "meraki_network.n_1"


def test_pinned_duplicate_assets_are_written_once(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """Identity-pinned resolution must still dedupe identical assets."""
    generator.generate(
        _graph(networks=(_network("N-1"),), devices=(), features=()), tmp_path
    )
    report = generator.generate(
        _graph(networks=(_network("N-1"), _network("N-1")), devices=(), features=()),
        tmp_path,
    )
    assert report.imports_written == 1
    assert [asset.address for asset in report.captured] == ["meraki_network.n_1"]


def test_empty_graph_writes_header_only_file(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    report = generator.generate(
        _graph(networks=(), devices=(), features=()), tmp_path
    )
    assert report.imports_written == 0
    assert "import {" not in report.imports_file.read_text(encoding="utf-8")


def test_captured_assets_carry_addresses_for_coverage(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """Every capturable asset lands in the report with its resolved
    address, so the coverage manifest and deletion detector see the
    full discovery picture — including state-tracked skips."""
    report = generator.generate(
        _graph(),
        tmp_path,
        existing_addresses=frozenset({"meraki_network.n_1"}),
    )
    by_address = {asset.address: asset for asset in report.captured}
    assert set(by_address) == {
        "meraki_network.n_1",
        "meraki_device.q2ab_cdef_ghij",
        "meraki_appliance_vlan.n_1_10",
    }
    assert report.captured_addresses == frozenset(by_address)
    assert by_address["meraki_network.n_1"].already_in_state is True
    assert by_address["meraki_network.n_1"].api_path == "/networks/{networkId}"
    assert by_address["meraki_device.q2ab_cdef_ghij"].already_in_state is False
    assert by_address["meraki_appliance_vlan.n_1_10"].import_id == "N_1,10"


def test_quiet_reaudit_suppresses_alerts_but_still_reports(
    generator: HclImportGenerator,
    tmp_path: Path,
    recorder: RecordingNotifier,
    caplog: pytest.LogCaptureFixture,
) -> None:
    """audit=False (same-run regeneration) must not re-dispatch findings."""
    graph = _graph(
        features=(
            FeatureConfiguration("/networks/{networkId}/unknownFeature", ("N_1",)),
        )
    )
    with caplog.at_level(logging.ERROR, logger="meraki2tf.hcl_generator"):
        report = generator.generate(graph, tmp_path, audit=False)

    assert len(report.unsupported) == 1  # the finding itself is never hidden
    assert recorder.events == []
    assert not any(
        "UNSUPPORTED FEATURE" in record.message for record in caplog.records
    )


def test_force_delete_identity_inserts_literal_false(
    tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """Group-policy-style identities import as <scope>,false,<id> so an
    import can never be armed to cascade a delete."""
    spec = {
        "openapi": "3.0.1",
        "paths": {
            "/networks/{networkId}/groupPolicies": {
                "get": {"operationId": "getPolicies", "tags": ["networks"]},
                "post": {"operationId": "createPolicy", "tags": ["networks"]},
            },
            "/networks/{networkId}/groupPolicies/{groupPolicyId}": {
                "get": {"operationId": "getPolicy", "tags": ["networks"]},
                "put": {"operationId": "updatePolicy", "tags": ["networks"]},
            },
        },
    }
    spec_path = tmp_path / "spec.json"
    spec_path.write_text(json.dumps(spec), encoding="utf-8")
    catalog = ProviderCatalog(
        resources={
            "meraki_network_group_policy": frozenset(
                {"force_delete", "id", "network_id"}
            ),
        },
        source="fixture",
    )
    generator = HclImportGenerator(
        OpenApiParser(spec_path), AlertDispatcher([recorder]), lambda: catalog
    )
    graph = NetworkGraph(
        organization_id="org-123",
        networks=(),
        devices=(),
        features=(
            FeatureConfiguration(
                "/networks/{networkId}/groupPolicies/{groupPolicyId}",
                ("N_1", "101"),
            ),
        ),
    )
    report = generator.generate(graph, tmp_path)
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 1
    assert "to = meraki_network_group_policy.n_1_101\n" in content
    assert 'id = "N_1,false,101"' in content


def test_unmatched_entity_is_flagged_as_provider_gap(
    spec_parser: OpenApiParser, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """A mutable entity the provider has no resource for must surface as
    an unsupported coverage gap, never as a guessed import."""
    stripped = {
        name: attrs
        for name, attrs in fixture_catalog().resources.items()
        if name != "meraki_sensor_relationships"
    }
    generator = HclImportGenerator(
        spec_parser,
        AlertDispatcher([recorder]),
        lambda: ProviderCatalog(resources=stripped, source="fixture"),
    )
    graph = NetworkGraph(
        organization_id="org-123",
        networks=(),
        devices=(),
        features=(
            FeatureConfiguration(
                "/networks/{networkId}/sensor/relationships", ("N_1",)
            ),
        ),
    )
    report = generator.generate(graph, tmp_path)
    assert report.imports_written == 0
    assert len(report.unsupported) == 1
    assert (
        "No CiscoDevNet/meraki provider resource matches"
        in report.unsupported[0].reason
    )
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED


def test_comma_bearing_id_component_is_flagged_unsupported(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """The provider splits compound import IDs positionally on commas;
    a doctored dump planting a comma inside a component would shift
    every later component (worst case arming a force_delete slot), so
    the asset is refused into the coverage manifest instead."""
    report = generator.generate(
        _graph(
            networks=(_network("N-1"), _network("true,123")),
            devices=(),
            features=(),
        ),
        tmp_path,
    )
    assert report.imports_written == 1
    reasons = {
        asset.identifiers: asset.reason for asset in report.unsupported
    }
    assert ("true,123",) in reasons
    assert "comma" in reasons[("true,123",)]
    content = report.imports_file.read_text(encoding="utf-8")
    assert "true,123" not in content


def test_duplicate_import_ids_become_explicit_records(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """A duplicated import ID is a discovered object; skipping it
    silently would leave the coverage totals unable to account for it
    (Cardinal Rule 2). It becomes a duplicate-id record naming its
    primary instead."""
    report = generator.generate(
        _graph(networks=(_network(), _network()), devices=(), features=()),
        tmp_path,
    )
    assert report.imports_written == 1
    assert len(report.duplicates) == 1
    duplicate = report.duplicates[0]
    assert duplicate.api_path == "/networks/{networkId}"
    assert duplicate.import_id == "org-123,N_1"
    assert duplicate.identifiers == ("N_1",)
    assert duplicate.primary_address == "meraki_network.n_1"
    # Accounting conserves the graph: 2 discovered → 1 captured + 1 dup.
    assert len(report.captured) + len(report.duplicates) == 2


def test_pinned_duplicates_are_recorded_too(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """The ledger-pinned dedupe arm must account duplicates exactly like
    the ordinal arm."""
    (tmp_path / ADDRESS_LEDGER_FILENAME).write_text(
        json.dumps({"addresses": {"meraki_network.n_1": "org-123,N_1"}}),
        encoding="utf-8",
    )
    report = generator.generate(
        _graph(networks=(_network(), _network()), devices=(), features=()),
        tmp_path,
    )
    assert len(report.duplicates) == 1
    assert report.duplicates[0].primary_address == "meraki_network.n_1"


def test_force_delete_single_component_identity_trails_false(
    tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """Arity-1 identities have no scope prefix to slot ``false``
    between; inserting at len-1 (= index 0) would shift the real ID out
    of its positional slot (``false,<id>``). The literal trails
    instead."""
    spec = {
        "openapi": "3.0.1",
        "paths": {
            "/widgets/{widgetId}": {
                "get": {"operationId": "getWidget", "tags": ["widgets"]},
                "put": {"operationId": "updateWidget", "tags": ["widgets"]},
            },
        },
    }
    spec_path = tmp_path / "spec.json"
    spec_path.write_text(json.dumps(spec), encoding="utf-8")
    catalog = ProviderCatalog(
        resources={"meraki_widget": frozenset({"force_delete", "id"})},
        source="fixture",
    )
    generator = HclImportGenerator(
        OpenApiParser(spec_path), AlertDispatcher([recorder]), lambda: catalog
    )
    graph = NetworkGraph(
        organization_id="org-123",
        networks=(),
        devices=(),
        features=(FeatureConfiguration("/widgets/{widgetId}", ("W1",)),),
    )
    report = generator.generate(graph, tmp_path)
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 1
    assert 'id = "W1,false"' in content


def test_config_template_bindings_flagged_as_a_kit_gap(
    tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """A network bound to a config template rebuilds STANDALONE from the
    kit, and the operator must be told.

    Regression (E2E r7): the provider's meraki_network has no attribute
    expressing the binding, so a --rebuild returns a template-governed
    site as a standalone one — silently. Nothing in the manifest, the
    runbook or the alerts mentioned it.
    """
    from meraki2tf.hcl_generator import (
        NETWORK_BIND_PATH,
        TEMPLATE_BINDING_REASON,
    )

    spec = {
        "openapi": "3.0.1",
        "paths": {
            "/networks/{networkId}": {
                "get": {"operationId": "getNetwork", "tags": ["networks"]},
                "put": {"operationId": "updateNetwork", "tags": ["networks"]},
            },
        },
    }
    spec_path = tmp_path / "spec.json"
    spec_path.write_text(json.dumps(spec), encoding="utf-8")
    generator = HclImportGenerator(
        OpenApiParser(spec_path), AlertDispatcher([recorder]), fixture_catalog
    )
    graph = NetworkGraph(
        organization_id="org-123",
        networks=(
            MerakiNetwork.from_payload(
                {"id": "N_1", "organizationId": "org-123", "name": "Bound",
                 "productTypes": ["appliance"], "configTemplateId": "T_1"}
            ),
            MerakiNetwork.from_payload(
                {"id": "N_2", "organizationId": "org-123", "name": "Free",
                 "productTypes": ["appliance"]}
            ),
        ),
        devices=(),
        features=(),
    )
    report = generator.generate(graph, tmp_path)

    bindings = [
        asset for asset in report.unsupported
        if asset.api_path == NETWORK_BIND_PATH
    ]
    assert [asset.identifiers for asset in bindings] == [("N_1",)]
    assert bindings[0].reason == TEMPLATE_BINDING_REASON
    # Counted with the spec-level gaps, so coverage totals still
    # reconcile against the objects discovery produced.
    assert report.spec_gap_count == len(bindings)
    assert any(
        event.event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED
        for event in recorder.events
    )


def test_write_only_endpoints_flagged_as_spec_level_gaps(
    tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """A PUT the API offers no read for holds configuration discovery
    can never see; every run must say so through the same exception-
    auditor rail as graph assets — with the spec-level count kept
    separate so coverage totals still reconcile against the graph."""
    from meraki2tf.hcl_generator import WRITE_ONLY_REASON

    spec = {
        "openapi": "3.0.1",
        "paths": {
            "/networks/{networkId}": {
                "get": {"operationId": "getNetwork", "tags": ["networks"]},
                "put": {"operationId": "updateNetwork", "tags": ["networks"]},
            },
            "/networks/{networkId}/appliance/sdwan/internetPolicies": {
                "put": {"operationId": "updateSdwan", "tags": ["appliance"]},
            },
        },
    }
    spec_path = tmp_path / "spec.json"
    spec_path.write_text(json.dumps(spec), encoding="utf-8")
    generator = HclImportGenerator(
        OpenApiParser(spec_path), AlertDispatcher([recorder]), fixture_catalog
    )
    graph = NetworkGraph(
        organization_id="org-123", networks=(), devices=(), features=()
    )
    report = generator.generate(graph, tmp_path)
    assert report.spec_gap_count == 1
    assert [asset.api_path for asset in report.unsupported] == [
        "/networks/{networkId}/appliance/sdwan/internetPolicies"
    ]
    assert report.unsupported[0].reason == WRITE_ONLY_REASON
    assert report.unsupported[0].identifiers == ()
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED

    # A quiet re-generation pass (heal rounds) reports but never
    # re-alerts.
    recorder.events.clear()
    quiet = generator.generate(graph, tmp_path, audit=False)
    assert quiet.spec_gap_count == 1
    assert recorder.events == []
