"""HCL translation engine and exception auditor behavior."""

import logging
from pathlib import Path

import pytest

from meraki2tf.alerts import AlertDispatcher, AlertEvent, EventType, Notifier
from meraki2tf.hcl_generator import HclImportGenerator
from meraki2tf.models import (
    FeatureConfiguration,
    MerakiDevice,
    MerakiNetwork,
    NetworkGraph,
)
from meraki2tf.openapi_parser import OpenApiParser


class RecordingNotifier(Notifier):
    channel = "recording"

    def __init__(self) -> None:
        self.events: list[AlertEvent] = []

    def send(self, event: AlertEvent) -> None:
        self.events.append(event)


@pytest.fixture()
def recorder() -> RecordingNotifier:
    return RecordingNotifier()


@pytest.fixture()
def generator(
    spec_parser: OpenApiParser, recorder: RecordingNotifier
) -> HclImportGenerator:
    return HclImportGenerator(spec_parser, AlertDispatcher([recorder]))


def _network(network_id: str = "N_1") -> MerakiNetwork:
    return MerakiNetwork.from_payload({"id": network_id, "organizationId": "org-123"})


def _graph(**overrides: tuple) -> NetworkGraph:  # type: ignore[type-arg]
    values = {
        "networks": (_network(),),
        "devices": (
            MerakiDevice.from_payload({"serial": "Q2AB-CDEF-GHIJ", "networkId": "N_1"}),
        ),
        "features": (
            FeatureConfiguration(
                "/networks/{networkId}/appliance/vlans/{vlanId}", ("N_1", "10")
            ),
        ),
    }
    values.update(overrides)
    return NetworkGraph(organization_id="org-123", **values)


def test_generates_import_blocks_for_all_mapped_assets(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    report = generator.generate(_graph(), tmp_path)
    content = report.imports_file.read_text(encoding="utf-8")

    assert report.imports_written == 3
    assert report.unsupported == ()
    assert recorder.events == []
    assert "to = meraki_networks.n_1\n" in content
    assert 'id = "N_1"' in content
    assert "to = meraki_devices.q2ab_cdef_ghij\n" in content
    assert "to = meraki_networks_appliance_vlans.n_1_10\n" in content
    assert 'id = "N_1,10"' in content
    assert content.startswith("# Generated by meraki2tf")


def test_unmapped_asset_triggers_exception_audit(
    generator: HclImportGenerator,
    tmp_path: Path,
    recorder: RecordingNotifier,
    caplog: pytest.LogCaptureFixture,
) -> None:
    graph = _graph(
        features=(
            FeatureConfiguration("/networks/{networkId}/unknownFeature", ("N_1",)),
        )
    )
    with caplog.at_level(logging.ERROR, logger="meraki2tf.hcl_generator"):
        report = generator.generate(graph, tmp_path)

    assert report.imports_written == 2  # network + device still written
    assert len(report.unsupported) == 1
    flagged = report.unsupported[0]
    assert flagged.api_path == "/networks/{networkId}/unknownFeature"
    assert "No Terraform resource maps" in flagged.reason
    assert any("UNSUPPORTED FEATURE" in record.message for record in caplog.records)

    assert len(recorder.events) == 1
    event = recorder.events[0]
    assert event.event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED
    assert event.details["identifiers"] == ["N_1"]


def test_id_component_arity_mismatch_is_flagged(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    graph = _graph(
        features=(
            FeatureConfiguration(
                "/networks/{networkId}/appliance/vlans/{vlanId}", ("N_1",)
            ),
        )
    )
    report = generator.generate(graph, tmp_path)
    assert len(report.unsupported) == 1
    assert "2 ID component(s)" in report.unsupported[0].reason
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED


def test_assets_already_in_state_are_skipped(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """Consecutive runs aggregate only the delta into existing state."""
    report = generator.generate(
        _graph(),
        tmp_path,
        existing_addresses=frozenset(
            {"meraki_networks.n_1", "meraki_devices.q2ab_cdef_ghij"}
        ),
    )
    content = report.imports_file.read_text(encoding="utf-8")

    assert report.skipped_existing == 2
    assert report.imports_written == 1  # only the VLAN is new
    assert "meraki_networks.n_1" not in content
    assert "meraki_devices.q2ab_cdef_ghij" not in content
    assert "to = meraki_networks_appliance_vlans.n_1_10\n" in content
    assert recorder.events == []  # skipping is not an exception-audit event


def test_duplicate_assets_are_written_once(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    report = generator.generate(
        _graph(networks=(_network(), _network()), devices=(), features=()), tmp_path
    )
    assert report.imports_written == 1


def test_labels_are_sanitized_to_valid_terraform_identifiers(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    report = generator.generate(
        _graph(networks=(_network("123-A.B"),), devices=(), features=()), tmp_path
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert "to = meraki_networks.r_123_a_b\n" in content
    assert 'id = "123-A.B"' in content


def test_empty_graph_writes_header_only_file(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    report = generator.generate(
        _graph(networks=(), devices=(), features=()), tmp_path
    )
    assert report.imports_written == 0
    assert "import {" not in report.imports_file.read_text(encoding="utf-8")
