"""HCL translation engine and exception auditor behavior."""

import json
import logging
from pathlib import Path

import pytest

from meraki2tf.alerts import AlertDispatcher, AlertEvent, EventType, Notifier
from meraki2tf.hcl_generator import HclImportGenerator
from meraki2tf.models import (
    FeatureConfiguration,
    MerakiDevice,
    MerakiNetwork,
    NetworkGraph,
)
from meraki2tf.openapi_parser import OpenApiParser
from meraki2tf.provider_catalog import ProviderCatalog
from conftest import fixture_catalog


class RecordingNotifier(Notifier):
    channel = "recording"

    def __init__(self) -> None:
        self.events: list[AlertEvent] = []

    def send(self, event: AlertEvent) -> None:
        self.events.append(event)


@pytest.fixture()
def recorder() -> RecordingNotifier:
    return RecordingNotifier()


@pytest.fixture()
def generator(
    spec_parser: OpenApiParser, recorder: RecordingNotifier
) -> HclImportGenerator:
    return HclImportGenerator(
        spec_parser, AlertDispatcher([recorder]), fixture_catalog
    )


def _network(network_id: str = "N_1") -> MerakiNetwork:
    return MerakiNetwork.from_payload({"id": network_id, "organizationId": "org-123"})


def _graph(**overrides: tuple) -> NetworkGraph:  # type: ignore[type-arg]
    values = {
        "networks": (_network(),),
        "devices": (
            MerakiDevice.from_payload({"serial": "Q2AB-CDEF-GHIJ", "networkId": "N_1"}),
        ),
        "features": (
            FeatureConfiguration(
                "/networks/{networkId}/appliance/vlans/{vlanId}", ("N_1", "10")
            ),
        ),
    }
    values.update(overrides)
    return NetworkGraph(organization_id="org-123", **values)


def test_generates_import_blocks_for_all_mapped_assets(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    report = generator.generate(_graph(), tmp_path)
    content = report.imports_file.read_text(encoding="utf-8")

    assert report.imports_written == 3
    assert report.unsupported == ()
    assert recorder.events == []
    assert "to = meraki_network.n_1\n" in content
    # meraki_network's identity demands the (always-known) org ID too.
    assert 'id = "org-123,N_1"' in content
    assert "to = meraki_device.q2ab_cdef_ghij\n" in content
    assert "to = meraki_appliance_vlan.n_1_10\n" in content
    assert 'id = "N_1,10"' in content
    assert content.startswith("# Generated by meraki2tf")


def test_unmapped_asset_triggers_exception_audit(
    generator: HclImportGenerator,
    tmp_path: Path,
    recorder: RecordingNotifier,
    caplog: pytest.LogCaptureFixture,
) -> None:
    graph = _graph(
        features=(
            FeatureConfiguration("/networks/{networkId}/unknownFeature", ("N_1",)),
        )
    )
    with caplog.at_level(logging.ERROR, logger="meraki2tf.hcl_generator"):
        report = generator.generate(graph, tmp_path)

    assert report.imports_written == 2  # network + device still written
    assert len(report.unsupported) == 1
    flagged = report.unsupported[0]
    assert flagged.api_path == "/networks/{networkId}/unknownFeature"
    assert "No Terraform resource maps" in flagged.reason
    assert any("UNSUPPORTED FEATURE" in record.message for record in caplog.records)

    assert len(recorder.events) == 1
    event = recorder.events[0]
    assert event.event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED
    assert event.details["identifiers"] == ["N_1"]


def test_id_component_arity_mismatch_is_flagged(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    graph = _graph(
        features=(
            FeatureConfiguration(
                "/networks/{networkId}/appliance/vlans/{vlanId}", ("N_1",)
            ),
        )
    )
    report = generator.generate(graph, tmp_path)
    assert len(report.unsupported) == 1
    assert "2 ID component(s)" in report.unsupported[0].reason
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED


def test_assets_already_in_state_are_skipped(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """Consecutive runs aggregate only the delta into existing state."""
    report = generator.generate(
        _graph(),
        tmp_path,
        existing_addresses=frozenset(
            {"meraki_network.n_1", "meraki_device.q2ab_cdef_ghij"}
        ),
    )
    content = report.imports_file.read_text(encoding="utf-8")

    assert report.skipped_existing == 2
    assert report.imports_written == 1  # only the VLAN is new
    assert "meraki_network.n_1" not in content
    assert "meraki_device.q2ab_cdef_ghij" not in content
    assert "to = meraki_appliance_vlan.n_1_10\n" in content
    assert recorder.events == []  # skipping is not an exception-audit event


def test_duplicate_assets_are_written_once(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    report = generator.generate(
        _graph(networks=(_network(), _network()), devices=(), features=()), tmp_path
    )
    assert report.imports_written == 1


def test_label_collisions_are_disambiguated_not_dropped(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """Distinct IDs that sanitize to the same label must all be captured."""
    report = generator.generate(
        _graph(
            networks=(_network("N-1"), _network("N.1"), _network("N_1")),
            devices=(),
            features=(),
        ),
        tmp_path,
    )
    content = report.imports_file.read_text(encoding="utf-8")

    assert report.imports_written == 3
    assert "to = meraki_network.n_1\n" in content
    assert "to = meraki_network.n_1_2\n" in content
    assert "to = meraki_network.n_1_3\n" in content
    assert 'id = "org-123,N-1"' in content
    assert 'id = "org-123,N.1"' in content
    assert 'id = "org-123,N_1"' in content


def test_collision_suffixes_stay_stable_against_existing_state(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """A colliding asset tracked under its suffixed address stays skipped."""
    graph = _graph(
        networks=(_network("N-1"), _network("N.1")), devices=(), features=()
    )
    report = generator.generate(
        graph,
        tmp_path,
        existing_addresses=frozenset({"meraki_network.n_1"}),
    )
    content = report.imports_file.read_text(encoding="utf-8")

    # N-1 (first) resolves to n_1 = already tracked; N.1 keeps n_1_2.
    assert report.skipped_existing == 1
    assert report.imports_written == 1
    assert "to = meraki_network.n_1_2\n" in content
    assert 'id = "org-123,N.1"' in content


def test_labels_are_sanitized_to_valid_terraform_identifiers(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    report = generator.generate(
        _graph(networks=(_network("123-A.B"),), devices=(), features=()), tmp_path
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert "to = meraki_network.r_123_a_b\n" in content
    assert 'id = "org-123,123-A.B"' in content


def test_folded_alias_path_is_flagged_not_misimported(
    generator: HclImportGenerator, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """/organizations/{organizationId}/networks folds into meraki_networks
    with matching arity — importing an org ID as a network must be refused."""
    graph = _graph(
        networks=(),
        devices=(),
        features=(
            FeatureConfiguration(
                "/organizations/{organizationId}/networks", ("org-123",)
            ),
        ),
    )
    report = generator.generate(graph, tmp_path)

    assert report.imports_written == 0
    assert len(report.unsupported) == 1
    assert "organization_id" in report.unsupported[0].reason
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED
    content = report.imports_file.read_text(encoding="utf-8")
    assert "org-123" not in content  # no wrong import block was emitted


def test_import_ids_are_hcl_escaped(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """IDs from arbitrary dump JSON must not break or inject into HCL."""
    report = generator.generate(
        _graph(networks=(_network('N"1${evil}'),), devices=(), features=()),
        tmp_path,
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 1
    assert 'id = "org-123,N\\"1$${evil}"' in content
    assert '"N"1' not in content  # no unterminated string literal


def test_newlines_in_import_ids_are_escaped(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """HCL quoted literals cannot span lines; a raw newline in one ID
    would corrupt the entire imports.tf."""
    report = generator.generate(
        _graph(networks=(_network("N\n1"),), devices=(), features=()), tmp_path
    )
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 1
    assert 'id = "org-123,N\\n1"' in content


def test_collision_suffixes_ignore_discovery_order(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """API listing order changes between runs must not reshuffle which
    colliding asset owns the base label vs the suffixed one."""
    ordered = generator.generate(
        _graph(networks=(_network("N-1"), _network("N.1")), devices=(), features=()),
        tmp_path,
    ).imports_file.read_text(encoding="utf-8")
    reordered = generator.generate(
        _graph(networks=(_network("N.1"), _network("N-1")), devices=(), features=()),
        tmp_path,
    ).imports_file.read_text(encoding="utf-8")
    assert ordered == reordered


def test_empty_graph_writes_header_only_file(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    report = generator.generate(
        _graph(networks=(), devices=(), features=()), tmp_path
    )
    assert report.imports_written == 0
    assert "import {" not in report.imports_file.read_text(encoding="utf-8")


def test_captured_assets_carry_addresses_for_coverage(
    generator: HclImportGenerator, tmp_path: Path
) -> None:
    """Every capturable asset lands in the report with its resolved
    address, so the coverage manifest and deletion detector see the
    full discovery picture — including state-tracked skips."""
    report = generator.generate(
        _graph(),
        tmp_path,
        existing_addresses=frozenset({"meraki_network.n_1"}),
    )
    by_address = {asset.address: asset for asset in report.captured}
    assert set(by_address) == {
        "meraki_network.n_1",
        "meraki_device.q2ab_cdef_ghij",
        "meraki_appliance_vlan.n_1_10",
    }
    assert report.captured_addresses == frozenset(by_address)
    assert by_address["meraki_network.n_1"].already_in_state is True
    assert by_address["meraki_network.n_1"].api_path == "/networks/{networkId}"
    assert by_address["meraki_device.q2ab_cdef_ghij"].already_in_state is False
    assert by_address["meraki_appliance_vlan.n_1_10"].import_id == "N_1,10"


def test_quiet_reaudit_suppresses_alerts_but_still_reports(
    generator: HclImportGenerator,
    tmp_path: Path,
    recorder: RecordingNotifier,
    caplog: pytest.LogCaptureFixture,
) -> None:
    """audit=False (same-run regeneration) must not re-dispatch findings."""
    graph = _graph(
        features=(
            FeatureConfiguration("/networks/{networkId}/unknownFeature", ("N_1",)),
        )
    )
    with caplog.at_level(logging.ERROR, logger="meraki2tf.hcl_generator"):
        report = generator.generate(graph, tmp_path, audit=False)

    assert len(report.unsupported) == 1  # the finding itself is never hidden
    assert recorder.events == []
    assert not any(
        "UNSUPPORTED FEATURE" in record.message for record in caplog.records
    )


def test_force_delete_identity_inserts_literal_false(
    tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """Group-policy-style identities import as <scope>,false,<id> so an
    import can never be armed to cascade a delete."""
    spec = {
        "openapi": "3.0.1",
        "paths": {
            "/networks/{networkId}/groupPolicies": {
                "get": {"operationId": "getPolicies", "tags": ["networks"]},
                "post": {"operationId": "createPolicy", "tags": ["networks"]},
            },
            "/networks/{networkId}/groupPolicies/{groupPolicyId}": {
                "get": {"operationId": "getPolicy", "tags": ["networks"]},
                "put": {"operationId": "updatePolicy", "tags": ["networks"]},
            },
        },
    }
    spec_path = tmp_path / "spec.json"
    spec_path.write_text(json.dumps(spec), encoding="utf-8")
    catalog = ProviderCatalog(
        resources={
            "meraki_network_group_policy": frozenset(
                {"force_delete", "id", "network_id"}
            ),
        },
        source="fixture",
    )
    generator = HclImportGenerator(
        OpenApiParser(spec_path), AlertDispatcher([recorder]), lambda: catalog
    )
    graph = NetworkGraph(
        organization_id="org-123",
        networks=(),
        devices=(),
        features=(
            FeatureConfiguration(
                "/networks/{networkId}/groupPolicies/{groupPolicyId}",
                ("N_1", "101"),
            ),
        ),
    )
    report = generator.generate(graph, tmp_path)
    content = report.imports_file.read_text(encoding="utf-8")
    assert report.imports_written == 1
    assert "to = meraki_network_group_policy.n_1_101\n" in content
    assert 'id = "N_1,false,101"' in content


def test_unmatched_entity_is_flagged_as_provider_gap(
    spec_parser: OpenApiParser, tmp_path: Path, recorder: RecordingNotifier
) -> None:
    """A mutable entity the provider has no resource for must surface as
    an unsupported coverage gap, never as a guessed import."""
    stripped = {
        name: attrs
        for name, attrs in fixture_catalog().resources.items()
        if name != "meraki_sensor_relationships"
    }
    generator = HclImportGenerator(
        spec_parser,
        AlertDispatcher([recorder]),
        lambda: ProviderCatalog(resources=stripped, source="fixture"),
    )
    graph = NetworkGraph(
        organization_id="org-123",
        networks=(),
        devices=(),
        features=(
            FeatureConfiguration(
                "/networks/{networkId}/sensor/relationships", ("N_1",)
            ),
        ),
    )
    report = generator.generate(graph, tmp_path)
    assert report.imports_written == 0
    assert len(report.unsupported) == 1
    assert (
        "No CiscoDevNet/meraki provider resource matches"
        in report.unsupported[0].reason
    )
    assert recorder.events[0].event_type is EventType.UNSUPPORTED_FEATURE_FLAGGED
