"""HCL translation engine: domain graph → modern Terraform import blocks.

Every discovered asset is resolved against the provider-resource match
table (see :mod:`~meraki2tf.resource_matcher`): spec-derived entities
matched onto the ``CiscoDevNet/meraki`` provider's own identity-schema
catalog, so every emitted resource type is one the installed provider
actually implements. The mapping is fully dynamic — spec + provider
metadata, no hard-coded tables. Assets that resolve are written as
declarative ``import {}`` blocks into ``imports.tf``; assets that
cannot be mapped are the exception auditor's territory: logged as
severe warnings and dispatched as ``UNSUPPORTED_FEATURE_FLAGGED``
alert payloads.

Import ID composition follows the provider's conventions: ordered path
parameter values joined by commas, with the organization ID prepended
when the resource's identity demands it (``meraki_network`` imports as
``"<organization_id>,<network_id>"``) and a literal ``"false"``
inserted for ``force_delete`` identities (group policies) so an import
can never cascade into a delete.
"""

from __future__ import annotations

import json
import logging
import re
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path

from meraki2tf.alerts import AlertDispatcher, unsupported_feature_flagged
from meraki2tf.models import UNREADABLE_MARKER, NetworkGraph
from meraki2tf.openapi_parser import OpenApiParser, snake_case
from meraki2tf.provider_catalog import ProviderCatalog
from meraki2tf.resource_matcher import MatchedResource, path_matches

logger = logging.getLogger(__name__)

IMPORTS_FILENAME = "imports.tf"

#: Workdir ledger pinning each import ID to the resource address it was
#: assigned. An asset's identity is its import ID, never its ordinal
#: position among colliding labels: the ledger keeps addresses stable
#: when the set of label-colliding assets changes between runs, so a
#: new colliding asset can never steal a state-tracked address (which
#: would fake ``already_in_state`` coverage and duplicate the shifted
#: object in state). Carries locators only, never secret values.
ADDRESS_LEDGER_FILENAME = "import_addresses.json"

#: Canonical entity addresses for the graph's first-class objects. These
#: are domain identities (how the Meraki API addresses a network or a
#: device), not mapping tables — the Terraform resource each one lands
#: in is still resolved dynamically from the spec.
NETWORK_API_PATH = "/networks/{networkId}"
DEVICE_API_PATH = "/devices/{serial}"

_LABEL_SANITIZER = re.compile(r"[^0-9a-z_]")
_PATH_PLACEHOLDER = re.compile(r"\{([^}]+)\}")

#: Every address this generator ever assigns is a validated provider
#: resource type plus a ``_LABEL_SANITIZER``-clean label, so anything
#: else in the ledger is tampering or corruption. Ledger keys are
#: written verbatim into ``imports.tf`` as ``to = <address>``; without
#: this gate a doctored workdir ledger could smuggle newlines/braces —
#: arbitrary HCL — into the kit, and the merge-forward in
#: ``_write_ledger`` would re-materialize it on every future run.
_ADDRESS_RE = re.compile(r"meraki_[a-z0-9_]+\.[a-z0-9_]+\Z")

_FILE_HEADER = """\
# Generated by meraki2tf — declarative import blocks for discovered assets.
# Do not edit by hand; re-run the pipeline to regenerate.
"""


@dataclass(frozen=True)
class ImportCandidate:
    """One asset addressed by API path template + ordered ID values."""

    api_path: str
    id_values: tuple[str, ...]
    #: Reason discovery could not read the endpoint, when it could not.
    #: Such an asset has no payload to build configuration from and its
    #: provider Read would fail the same way, so it must be audited as
    #: unsupported instead of imported.
    unreadable: str | None = None


@dataclass(frozen=True)
class UnsupportedAsset:
    """One asset the exception auditor flagged as untranslatable."""

    api_path: str
    reason: str
    identifiers: tuple[str, ...]


@dataclass(frozen=True)
class CapturedAsset:
    """One asset Terraform can rebuild, resolved to its resource address."""

    address: str
    api_path: str
    import_id: str
    #: True when the state file already tracked the address, so no new
    #: import block was written for it this run.
    already_in_state: bool
    #: The asset's raw path values, exactly as discovery addressed it —
    #: the key that leads back to the discovered payload (the import_id
    #: above may carry injected org-prefix/force_delete components).
    identifiers: tuple[str, ...] = ()


@dataclass(frozen=True)
class GenerationReport:
    """Outcome of one HCL generation pass."""

    imports_file: Path
    imports_written: int
    unsupported: tuple[UnsupportedAsset, ...]
    #: Assets skipped because the state file already tracks them.
    skipped_existing: int = 0
    #: Every capturable asset with its resolved address — the coverage
    #: manifest's raw material and the deletion detector's reference set.
    captured: tuple[CapturedAsset, ...] = ()
    #: Terraform resource types whose endpoint(s) could not be read
    #: during discovery. Their objects are absent from ``captured``
    #: without being absent from Meraki, so the deletion detector must
    #: not treat state-tracked resources of these types as deleted.
    unreadable_types: frozenset[str] = frozenset()

    @property
    def captured_addresses(self) -> frozenset[str]:
        """Addresses of every asset discovery found this run."""
        return frozenset(asset.address for asset in self.captured)


class HclImportGenerator:
    """Writes ``imports.tf`` and audits unmappable assets."""

    def __init__(
        self,
        parser: OpenApiParser,
        dispatcher: AlertDispatcher,
        catalog_provider: Callable[[], ProviderCatalog],
    ) -> None:
        self._parser = parser
        self._dispatcher = dispatcher
        #: Resolved lazily on first generate(): live keyed runs dump the
        #: installed provider's schema, which requires the workspace to
        #: be prepared/initialized first — construction time is too early.
        self._catalog_provider = catalog_provider
        self._matches: dict[str, MatchedResource | None] | None = None

    @property
    def parser(self) -> OpenApiParser:
        """The spec parser driving generation — shared with the DR
        runbook/replayer so replay operations derive from the same
        document (no second source of endpoint truth)."""
        return self._parser

    def _match_table(self) -> dict[str, MatchedResource | None]:
        if self._matches is None:
            self._matches = path_matches(self._parser, self._catalog_provider())
        return self._matches

    def generate(
        self,
        graph: NetworkGraph,
        workdir: Path,
        existing_addresses: frozenset[str] = frozenset(),
        audit: bool = True,
        suppress_addresses: frozenset[str] = frozenset(),
    ) -> GenerationReport:
        """Translate the graph into import blocks under ``workdir``.

        ``existing_addresses`` are resources the state file already
        tracks; they are skipped so consecutive runs aggregate only the
        delta instead of re-importing everything from zero. ``audit``
        controls the exception auditor's side effects (error logs and
        UNSUPPORTED_FEATURE_FLAGGED alerts); a same-run regeneration
        pass disables it so identical findings are not dispatched twice.
        ``suppress_addresses`` are resources the plan loop already
        dropped as unexpressible this run: a regeneration pass must not
        write their import blocks back, or every heal round re-pays the
        validation failures and an extra full plan. They stay in
        ``captured`` so downstream accounting (coverage, deletion
        detection) is unchanged — the reconciliation drop report is
        what marks them unsupported.
        """
        matches = self._match_table()
        ledger = self._load_ledger(workdir)
        #: import ID → the address a previous run assigned it.
        pins: dict[str, str] = {}
        for ledger_address, owner in ledger.items():
            pins.setdefault(owner, ledger_address)

        blocks: list[str] = []
        #: address → import ID, so identical assets dedupe while distinct
        #: assets whose IDs sanitize to the same label get disambiguated.
        seen_addresses: dict[str, str] = {}
        captured: list[CapturedAsset] = []
        unsupported: list[UnsupportedAsset] = []
        skipped_existing = 0

        unreadable_types: set[str] = set()
        for candidate in self._candidates(graph):
            if candidate.unreadable is not None:
                unreadable_match = matches.get(candidate.api_path)
                if unreadable_match is not None:
                    unreadable_types.add(unreadable_match.terraform_name)
                unsupported.append(
                    self._flag(
                        candidate,
                        "Endpoint could not be read during discovery "
                        f"({candidate.unreadable}); its objects are absent "
                        "from the kit and must be verified manually.",
                        audit=audit,
                    )
                )
                continue
            if candidate.api_path not in matches:
                unsupported.append(
                    self._flag(
                        candidate,
                        "No Terraform resource maps to this API path.",
                        audit=audit,
                    )
                )
                continue
            match = matches[candidate.api_path]
            if match is None:
                unsupported.append(
                    self._flag(
                        candidate,
                        "No CiscoDevNet/meraki provider resource matches "
                        "this endpoint.",
                        audit=audit,
                    )
                )
                continue
            expected = match.import_id_components
            provided = tuple(
                snake_case(name)
                for name in _PATH_PLACEHOLDER.findall(candidate.api_path)
            )
            if provided != expected:
                # A folded collection alias (e.g. /organizations/{organizationId}
                # /networks → meraki_network) can coincide in arity while
                # carrying the wrong ID components entirely — importing an
                # organization ID as a network. Semantics must match, not
                # just the count.
                unsupported.append(
                    self._flag(
                        candidate,
                        f"Import ID needs ({','.join(expected)}); this asset "
                        f"is addressed by ({','.join(provided) or 'none'}).",
                        audit=audit,
                    )
                )
                continue
            if len(candidate.id_values) != len(expected):
                unsupported.append(
                    self._flag(
                        candidate,
                        f"Import needs {len(expected)} ID component(s) "
                        f"({','.join(expected)}), asset carries "
                        f"{len(candidate.id_values)}.",
                        audit=audit,
                    )
                )
                continue
            import_id = ",".join(
                self._import_components(match, candidate, graph.organization_id)
            )
            base = f"{match.terraform_name}.{self._label(candidate.id_values)}"
            address = self._resolve_address(
                base, import_id, seen_addresses, ledger, pins
            )
            if address is None:
                logger.debug("Skipping duplicate import of id %s", import_id)
                continue
            seen_addresses[address] = import_id
            already_tracked = address in existing_addresses
            captured.append(
                CapturedAsset(
                    address=address,
                    api_path=candidate.api_path,
                    import_id=import_id,
                    already_in_state=already_tracked,
                    identifiers=candidate.id_values,
                )
            )
            if already_tracked:
                skipped_existing += 1
                logger.debug("Skipping %s; already tracked in state.", address)
                continue
            if address in suppress_addresses:
                logger.debug(
                    "Skipping %s; dropped as unexpressible earlier this run.",
                    address,
                )
                continue
            blocks.append(
                f'import {{\n  to = {address}\n'
                f'  id = "{self._quote_hcl(import_id)}"\n}}\n'
            )

        imports_file = workdir / IMPORTS_FILENAME
        imports_file.write_text(
            _FILE_HEADER + "\n" + "\n".join(blocks), encoding="utf-8"
        )
        self._write_ledger(
            workdir,
            ledger,
            {asset.address: asset.import_id for asset in captured},
            existing_addresses,
        )
        logger.info(
            "Wrote %d import block(s) to %s (%d already in state, "
            "%d unsupported asset(s) flagged).",
            len(blocks), imports_file, skipped_existing, len(unsupported),
        )
        return GenerationReport(
            imports_file=imports_file,
            imports_written=len(blocks),
            unsupported=tuple(unsupported),
            skipped_existing=skipped_existing,
            captured=tuple(captured),
            unreadable_types=frozenset(unreadable_types),
        )

    @staticmethod
    def _import_components(
        match: MatchedResource, candidate: ImportCandidate, organization_id: str
    ) -> tuple[str, ...]:
        """Ordered import-ID components per the provider's conventions.

        The asset's path values are the base. Identities carrying
        ``force_delete`` (group policies) take a literal ``"false"``
        before the item ID — imports must never be armed to cascade a
        delete. Identities demanding an ``organization_id`` the path
        does not carry get the always-known organization prepended
        (``meraki_network`` → ``"<organization_id>,<network_id>"``).
        """
        components = list(candidate.id_values)
        if match.has_force_delete:
            components.insert(len(components) - 1, "false")
        if match.needs_org_prefix:
            components.insert(0, organization_id)
        return tuple(components)

    @staticmethod
    def _candidates(graph: NetworkGraph) -> list[ImportCandidate]:
        candidates = [
            ImportCandidate(NETWORK_API_PATH, (network.network_id,))
            for network in graph.networks
        ]
        candidates.extend(
            ImportCandidate(DEVICE_API_PATH, (device.serial,))
            for device in graph.devices
        )
        candidates.extend(
            ImportCandidate(
                feature.api_path,
                feature.path_values,
                unreadable=feature.payload.get(UNREADABLE_MARKER),
            )
            for feature in graph.features
        )
        # Sorted so collision-suffix assignment in _resolve_address does
        # not depend on API listing order, which can change between runs.
        return sorted(candidates, key=lambda c: (c.api_path, c.id_values))

    def _flag(
        self, candidate: ImportCandidate, reason: str, audit: bool = True
    ) -> UnsupportedAsset:
        """Exception auditor: severe log + UNSUPPORTED_FEATURE_FLAGGED alert."""
        if audit:
            logger.error(
                "UNSUPPORTED FEATURE: %s (ids=%s) — %s",
                candidate.api_path, ",".join(candidate.id_values) or "<none>", reason,
            )
            self._dispatcher.dispatch(
                unsupported_feature_flagged(
                    api_path=candidate.api_path,
                    reason=reason,
                    identifiers=candidate.id_values,
                )
            )
        return UnsupportedAsset(
            api_path=candidate.api_path,
            reason=reason,
            identifiers=candidate.id_values,
        )

    @staticmethod
    def _quote_hcl(value: str) -> str:
        """Escape a raw ID for a quoted HCL string literal.

        Dump-mode snapshots feed arbitrary JSON values into import IDs;
        an unescaped ``"``, ``\\``, ``${``, ``%{`` or a raw newline
        would break the whole imports.tf parse or inject an
        interpolation expression. JSON also admits lone UTF-16
        surrogates (``"\\ud800"``), which the UTF-8 artifact write
        cannot encode — they are replaced up front so a corrupted dump
        cannot crash the run at write time.
        """
        value = value.encode("utf-8", errors="replace").decode("utf-8")
        return (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
            .replace("${", "$${")
            .replace("%{", "%%{")
        )

    @staticmethod
    def _resolve_address(
        base: str,
        import_id: str,
        seen: dict[str, str],
        ledger: Mapping[str, str],
        pins: Mapping[str, str],
    ) -> str | None:
        """Unique address for the asset, or None for a true duplicate.

        Distinct IDs can sanitize to the same label (``N-1`` and ``N.1``
        both become ``n_1``); dropping one would silently lose an asset
        from the DR kit, so collisions get a deterministic numeric
        suffix instead. The asset's identity is its import ID, never its
        ordinal position among colliding labels: an address the workdir
        ledger pins to this ID is reused verbatim (so previously
        assigned — and state-tracked — addresses survive a new colliding
        asset appearing), and ordinal probing never claims an address
        the ledger records as belonging to a different ID (so a dead
        object's slot is not silently inherited while its state entry
        awaits deletion review). Without a ledger, candidate order is
        stable, so the same graph always yields the same addresses
        across runs — and the same addresses previous tool versions
        assigned.
        """
        pinned = pins.get(import_id)
        if pinned is not None and (pinned == base or pinned.startswith(f"{base}_")):
            # A pin whose label no longer matches (resource type or
            # label derivation changed) is stale and falls through to
            # ordinal assignment instead of resurrecting the old name.
            return None if pinned in seen else pinned
        address, counter = base, 2
        while address in seen or ledger.get(address, import_id) != import_id:
            if seen.get(address) == import_id:
                return None
            address = f"{base}_{counter}"
            counter += 1
        return address

    @staticmethod
    def _load_ledger(workdir: Path) -> dict[str, str]:
        """Previous runs' address → import-ID assignments, or ``{}``.

        A missing ledger is the normal first run against a workdir; a
        corrupt or alien document degrades to ordinal assignment with a
        warning — exactly the pre-ledger behavior — because a broken
        sidecar file must never fail the DR run.
        """
        path = workdir / ADDRESS_LEDGER_FILENAME
        if not path.exists():
            return {}
        try:
            document = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            logger.warning(
                "Address ledger %s is unreadable (%s); collision suffixes "
                "fall back to ordinal assignment this run.", path, exc,
            )
            return {}
        addresses = (
            document.get("addresses") if isinstance(document, Mapping) else None
        )
        if not isinstance(addresses, Mapping):
            logger.warning(
                "Address ledger %s has no 'addresses' object; collision "
                "suffixes fall back to ordinal assignment this run.", path,
            )
            return {}
        entries = {
            str(address): owner
            for address, owner in addresses.items()
            if isinstance(owner, str)
        }
        valid = {
            address: owner
            for address, owner in entries.items()
            if _ADDRESS_RE.fullmatch(address)
        }
        if len(valid) != len(entries):
            logger.warning(
                "Address ledger %s carries %d entr(ies) that are not "
                "well-formed resource addresses; ignoring them (possible "
                "tampering — this generator never writes such keys).",
                path, len(entries) - len(valid),
            )
        return valid

    @staticmethod
    def _write_ledger(
        workdir: Path,
        previous: Mapping[str, str],
        assignments: Mapping[str, str],
        existing_addresses: frozenset[str],
    ) -> None:
        """Persist this run's assignments, retaining state-tracked pins.

        Entries for addresses not captured this run are kept while the
        state file still tracks them (a deleted object's slot must stay
        reserved until its pending-deletion review removes it from
        state) and pruned once it does not — so the ledger never grows
        beyond the state it protects.
        """
        merged = {
            address: owner
            for address, owner in previous.items()
            if address in existing_addresses and address not in assignments
        }
        merged.update(assignments)
        document = {"addresses": dict(sorted(merged.items()))}
        (workdir / ADDRESS_LEDGER_FILENAME).write_text(
            json.dumps(document, indent=1) + "\n", encoding="utf-8"
        )

    @staticmethod
    def _label(id_values: tuple[str, ...]) -> str:
        """Sanitize ID values into a valid Terraform resource label."""
        label = _LABEL_SANITIZER.sub("_", "_".join(id_values).lower()) or "asset"
        if not (label[0].isalpha() or label[0] == "_"):
            label = f"r_{label}"
        return label
