"""HCL translation engine: domain graph → modern Terraform import blocks.

Every discovered asset is resolved against the OpenAPI-derived lookup
table (see :class:`~meraki2tf.openapi_parser.OpenApiParser`) — the
mapping from API path to ``CiscoDevNet/meraki`` resource name is fully
dynamic. Assets that resolve are written as declarative ``import {}``
blocks into ``imports.tf``; assets that cannot be mapped are the
exception auditor's territory: logged as severe warnings and dispatched
as ``UNSUPPORTED_FEATURE_FLAGGED`` alert payloads.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

from meraki2tf.alerts import AlertDispatcher, unsupported_feature_flagged
from meraki2tf.models import NetworkGraph
from meraki2tf.openapi_parser import OpenApiParser, snake_case

logger = logging.getLogger(__name__)

IMPORTS_FILENAME = "imports.tf"

#: Canonical entity addresses for the graph's first-class objects. These
#: are domain identities (how the Meraki API addresses a network or a
#: device), not mapping tables — the Terraform resource each one lands
#: in is still resolved dynamically from the spec.
NETWORK_API_PATH = "/networks/{networkId}"
DEVICE_API_PATH = "/devices/{serial}"

_LABEL_SANITIZER = re.compile(r"[^0-9a-z_]")
_PATH_PLACEHOLDER = re.compile(r"\{([^}]+)\}")

_FILE_HEADER = """\
# Generated by meraki2tf — declarative import blocks for discovered assets.
# Do not edit by hand; re-run the pipeline to regenerate.
"""


@dataclass(frozen=True)
class ImportCandidate:
    """One asset addressed by API path template + ordered ID values."""

    api_path: str
    id_values: tuple[str, ...]


@dataclass(frozen=True)
class UnsupportedAsset:
    """One asset the exception auditor flagged as untranslatable."""

    api_path: str
    reason: str
    identifiers: tuple[str, ...]


@dataclass(frozen=True)
class GenerationReport:
    """Outcome of one HCL generation pass."""

    imports_file: Path
    imports_written: int
    unsupported: tuple[UnsupportedAsset, ...]
    #: Assets skipped because the state file already tracks them.
    skipped_existing: int = 0


class HclImportGenerator:
    """Writes ``imports.tf`` and audits unmappable assets."""

    def __init__(self, parser: OpenApiParser, dispatcher: AlertDispatcher) -> None:
        self._parser = parser
        self._dispatcher = dispatcher

    def generate(
        self,
        graph: NetworkGraph,
        workdir: Path,
        existing_addresses: frozenset[str] = frozenset(),
    ) -> GenerationReport:
        """Translate the graph into import blocks under ``workdir``.

        ``existing_addresses`` are resources the state file already
        tracks; they are skipped so consecutive runs aggregate only the
        delta instead of re-importing everything from zero.
        """
        lookup = self._parser.endpoint_lookup()
        mappings = self._parser.resource_mappings()

        blocks: list[str] = []
        #: address → import ID, so identical assets dedupe while distinct
        #: assets whose IDs sanitize to the same label get disambiguated.
        seen_addresses: dict[str, str] = {}
        unsupported: list[UnsupportedAsset] = []
        skipped_existing = 0

        for candidate in self._candidates(graph):
            terraform_name = lookup.get(candidate.api_path)
            if terraform_name is None:
                unsupported.append(
                    self._flag(candidate, "No Terraform resource maps to this API path.")
                )
                continue
            expected = mappings[terraform_name].id_components
            provided = tuple(
                snake_case(name)
                for name in _PATH_PLACEHOLDER.findall(candidate.api_path)
            )
            if provided != expected:
                # A folded collection alias (e.g. /organizations/{organizationId}
                # /networks → meraki_networks) can coincide in arity while
                # carrying the wrong ID components entirely — importing an
                # organization ID as a network. Semantics must match, not
                # just the count.
                unsupported.append(
                    self._flag(
                        candidate,
                        f"Import ID needs ({','.join(expected)}); this asset "
                        f"is addressed by ({','.join(provided) or 'none'}).",
                    )
                )
                continue
            if len(candidate.id_values) != len(expected):
                unsupported.append(
                    self._flag(
                        candidate,
                        f"Import needs {len(expected)} ID component(s) "
                        f"({','.join(expected)}), asset carries "
                        f"{len(candidate.id_values)}.",
                    )
                )
                continue
            import_id = ",".join(candidate.id_values)
            base = f"{terraform_name}.{self._label(candidate.id_values)}"
            address = self._resolve_address(base, import_id, seen_addresses)
            if address is None:
                logger.debug("Skipping duplicate import of id %s", import_id)
                continue
            seen_addresses[address] = import_id
            if address in existing_addresses:
                skipped_existing += 1
                logger.debug("Skipping %s; already tracked in state.", address)
                continue
            blocks.append(
                f'import {{\n  to = {address}\n'
                f'  id = "{self._quote_hcl(import_id)}"\n}}\n'
            )

        imports_file = workdir / IMPORTS_FILENAME
        imports_file.write_text(
            _FILE_HEADER + "\n" + "\n".join(blocks), encoding="utf-8"
        )
        logger.info(
            "Wrote %d import block(s) to %s (%d already in state, "
            "%d unsupported asset(s) flagged).",
            len(blocks), imports_file, skipped_existing, len(unsupported),
        )
        return GenerationReport(
            imports_file=imports_file,
            imports_written=len(blocks),
            unsupported=tuple(unsupported),
            skipped_existing=skipped_existing,
        )

    @staticmethod
    def _candidates(graph: NetworkGraph) -> list[ImportCandidate]:
        candidates = [
            ImportCandidate(NETWORK_API_PATH, (network.network_id,))
            for network in graph.networks
        ]
        candidates.extend(
            ImportCandidate(DEVICE_API_PATH, (device.serial,))
            for device in graph.devices
        )
        candidates.extend(
            ImportCandidate(feature.api_path, feature.path_values)
            for feature in graph.features
        )
        # Sorted so collision-suffix assignment in _resolve_address does
        # not depend on API listing order, which can change between runs.
        return sorted(candidates, key=lambda c: (c.api_path, c.id_values))

    def _flag(self, candidate: ImportCandidate, reason: str) -> UnsupportedAsset:
        """Exception auditor: severe log + UNSUPPORTED_FEATURE_FLAGGED alert."""
        logger.error(
            "UNSUPPORTED FEATURE: %s (ids=%s) — %s",
            candidate.api_path, ",".join(candidate.id_values) or "<none>", reason,
        )
        self._dispatcher.dispatch(
            unsupported_feature_flagged(
                api_path=candidate.api_path,
                reason=reason,
                identifiers=candidate.id_values,
            )
        )
        return UnsupportedAsset(
            api_path=candidate.api_path,
            reason=reason,
            identifiers=candidate.id_values,
        )

    @staticmethod
    def _quote_hcl(value: str) -> str:
        """Escape a raw ID for a quoted HCL string literal.

        Dump-mode snapshots feed arbitrary JSON values into import IDs;
        an unescaped ``"``, ``\\``, ``${``, ``%{`` or a raw newline
        would break the whole imports.tf parse or inject an
        interpolation expression.
        """
        return (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
            .replace("${", "$${")
            .replace("%{", "%%{")
        )

    @staticmethod
    def _resolve_address(
        base: str, import_id: str, seen: dict[str, str]
    ) -> str | None:
        """Unique address for the asset, or None for a true duplicate.

        Distinct IDs can sanitize to the same label (``N-1`` and ``N.1``
        both become ``n_1``); dropping one would silently lose an asset
        from the DR kit, so collisions get a deterministic numeric
        suffix instead. Candidate order is stable, so the same graph
        always yields the same addresses across runs.
        """
        address, counter = base, 2
        while address in seen:
            if seen[address] == import_id:
                return None
            address = f"{base}_{counter}"
            counter += 1
        return address

    @staticmethod
    def _label(id_values: tuple[str, ...]) -> str:
        """Sanitize ID values into a valid Terraform resource label."""
        label = _LABEL_SANITIZER.sub("_", "_".join(id_values).lower()) or "asset"
        if not (label[0].isalpha() or label[0] == "_"):
            label = f"r_{label}"
        return label
