"""Local Terraform CLI runner built on the standard subprocess module.

Owns the execution workspace: writes the ``provider.tf`` anchor for the
``CiscoDevNet/meraki`` source with a local backend pinned to the state
file, runs ``init``, and executes the speculative generation plan
(``terraform plan -generate-config-out=...``).

Read-only guarantee: the pipeline never mutates the Meraki
organization. ``terraform apply`` exists solely as
:meth:`TerraformRunner.rebuild_apply`, reachable only through the
explicit, human-invoked ``--rebuild --confirm`` disaster-recovery
action — never through a scheduled or normal run.

State lifecycle: the state file location is explicit (``--state-file``,
defaulting to ``terraform.tfstate`` inside the workspace). An existing
file is reused so consecutive runs only import the delta; the runner
reports which resource addresses the state already tracks, so upstream
generation skips re-importing them.

Security: the Meraki token never touches disk — the provider block is
written credential-free and the ``meraki`` Terraform provider reads
``MERAKI_DASHBOARD_API_KEY`` from the process environment on its own.
"""

from __future__ import annotations

import json
import logging
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

PROVIDER_FILENAME = "provider.tf"
GENERATED_CONFIG_FILENAME = "generated_resources.tf"
#: Persistent accumulated configuration: every plan's freshly generated
#: config is folded in here, so resources keep their HCL across runs.
AGGREGATED_CONFIG_FILENAME = "resources.tf"
DEFAULT_STATE_FILENAME = "terraform.tfstate"

_PROVIDER_TF_TEMPLATE = """\
# Generated by meraki2tf — provider anchor for the execution workspace.
terraform {{
  backend "local" {{
    # State persists here across runs; point --state-file at an existing
    # state to keep aggregating into it instead of starting from zero.
    path = "{state_path}"
  }}

  required_providers {{
    meraki = {{
      source = "CiscoDevNet/meraki"
    }}
  }}
}}

provider "meraki" {{
  # Credentials are read from the MERAKI_DASHBOARD_API_KEY environment
  # variable by the provider itself and are never written to disk.
}}
"""

#: ``terraform plan -detailed-exitcode`` contract.
_PLAN_NO_CHANGES = 0
_PLAN_ERROR = 1
_PLAN_CHANGES_PRESENT = 2

#: Terraform's human plan summary, e.g.
#: ``Plan: 875 to import, 0 to add, 2 to change, 0 to destroy.``
_PLAN_SUMMARY_RE = re.compile(
    r"Plan: (?:(?P<imports>\d+) to import, )?(?P<add>\d+) to add, "
    r"(?P<change>\d+) to change, (?P<destroy>\d+) to destroy"
)


class TerraformError(RuntimeError):
    """A terraform invocation failed; message carries the CLI diagnostics."""


def _hcl_quote(value: str) -> str:
    """Escape a raw value for interpolation into a quoted HCL literal."""
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
        .replace("${", "$${")
        .replace("%{", "%%{")
    )


@dataclass(frozen=True)
class PlanCounts:
    """Change counts parsed from a terraform plan summary line."""

    imports: int
    add: int
    change: int
    destroy: int

    @property
    def has_real_changes(self) -> bool:
        """True when the plan proposes mutations, not just imports."""
        return (self.add + self.change + self.destroy) > 0


@dataclass(frozen=True)
class TerraformCommandResult:
    """Captured outcome of one terraform subprocess invocation."""

    command: tuple[str, ...]
    returncode: int
    stdout: str
    stderr: str

    @property
    def has_changes(self) -> bool:
        """True for ``plan -detailed-exitcode`` runs that found a delta."""
        return self.returncode == _PLAN_CHANGES_PRESENT

    @property
    def plan_counts(self) -> PlanCounts | None:
        """Parsed plan summary counts, or None when no summary is present.

        Lets the orchestrator report exactly how much of the snapshot is
        still pending aggregation into state versus real change pressure.
        """
        match = _PLAN_SUMMARY_RE.search(self.stdout)
        if match is None:
            return None
        return PlanCounts(
            imports=int(match.group("imports") or 0),
            add=int(match.group("add")),
            change=int(match.group("change")),
            destroy=int(match.group("destroy")),
        )

    @property
    def has_drift(self) -> bool:
        """True when the plan proposes real changes (add/change/destroy).

        Pending ``import`` blocks are not drift — a plan that only
        imports means discovery found resources the state does not track
        yet, which is the tool's normal snapshot-growing behavior. Falls
        back to the ``-detailed-exitcode`` contract when no summary line
        can be parsed, so an unrecognized plan errs toward alerting.
        """
        counts = self.plan_counts
        if counts is None:
            return self.returncode == _PLAN_CHANGES_PRESENT
        return counts.has_real_changes


class TerraformRunner:
    """Drives the local ``terraform`` binary inside a managed workspace."""

    def __init__(
        self,
        workdir: Path,
        executable: str = "terraform",
        state_path: Path | None = None,
    ) -> None:
        self._workdir = workdir
        self._executable = executable
        self._state_path = (
            state_path if state_path is not None else workdir / DEFAULT_STATE_FILENAME
        ).resolve()

    @property
    def workdir(self) -> Path:
        return self._workdir

    @property
    def state_path(self) -> Path:
        return self._state_path

    def prepare_workspace(self) -> Path:
        """Create the execution directory and anchor provider + state backend."""
        self._workdir.mkdir(parents=True, exist_ok=True)
        self._state_path.parent.mkdir(parents=True, exist_ok=True)
        provider_file = self._workdir / PROVIDER_FILENAME
        provider_file.write_text(
            _PROVIDER_TF_TEMPLATE.format(state_path=_hcl_quote(str(self._state_path))),
            encoding="utf-8",
        )
        if self._state_path.exists():
            logger.info("Reusing existing Terraform state at %s.", self._state_path)
        else:
            logger.info(
                "No Terraform state at %s; each run regenerates the full "
                "import snapshot (state is only written when you apply, "
                "e.g. via --rebuild --confirm).",
                self._state_path,
            )
        logger.debug("Workspace prepared at %s", self._workdir)
        return provider_file

    def existing_addresses(self) -> frozenset[str]:
        """Resource addresses (``type.name``) already tracked in the state.

        Lets generation skip re-importing resources from prior runs so
        consecutive executions only aggregate the delta.
        """
        if not self._state_path.exists():
            return frozenset()
        try:
            document = json.loads(self._state_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise TerraformError(
                f"Existing state file {self._state_path} is unreadable: {exc}"
            ) from exc
        resources = document.get("resources", []) if isinstance(document, dict) else []
        addresses = frozenset(
            f"{resource['type']}.{resource['name']}"
            for resource in resources
            if isinstance(resource, dict)
            and resource.get("mode") == "managed"
            and resource.get("type")
            and resource.get("name")
        )
        logger.info(
            "Existing state tracks %d managed resource(s).", len(addresses)
        )
        return addresses

    def init(self) -> TerraformCommandResult:
        # -reconfigure keeps init idempotent when the backend/state path
        # differs from a previous run in the same workspace.
        return self._run("init", "-input=false", "-no-color", "-reconfigure")

    def plan_with_generation(self) -> TerraformCommandResult:
        """Speculative check: plan imports and generate missing config.

        Returns with ``has_changes`` reflecting the ``-detailed-exitcode``
        contract (0 = state in sync, 2 = delta present).
        """
        # terraform refuses to overwrite an existing generation target;
        # a leftover file from an interrupted run is absorbed first.
        self._absorb_generated_config()
        result = self._run(
            "plan",
            "-input=false",
            "-no-color",
            "-detailed-exitcode",
            f"-generate-config-out={GENERATED_CONFIG_FILENAME}",
            allowed=(_PLAN_NO_CHANGES, _PLAN_CHANGES_PRESENT),
        )
        self._absorb_generated_config()
        return result

    def _absorb_generated_config(self) -> None:
        """Fold freshly generated config into the persistent resources.tf.

        Deleting the generation target instead (the naive fix for
        terraform's refusal to overwrite it) would leave state-tracked
        resources with no configuration, so every subsequent plan would
        propose destroying them — a false drift alert, and a workspace
        that tears the organization down if rebuild-applied. Accumulating
        keeps the workspace a faithful, apply-safe DR kit and lets the
        plan compare tracked resources against their captured baseline.
        """
        generated = self._workdir / GENERATED_CONFIG_FILENAME
        if not generated.exists():
            return
        content = generated.read_text(encoding="utf-8")
        if content.strip():
            aggregated = self._workdir / AGGREGATED_CONFIG_FILENAME
            with aggregated.open("a", encoding="utf-8") as handle:
                handle.write(content if content.endswith("\n") else content + "\n")
            logger.info(
                "Absorbed newly generated configuration into %s.",
                AGGREGATED_CONFIG_FILENAME,
            )
        generated.unlink()

    def has_config_baseline(self) -> bool:
        """Whether the workspace holds accumulated resource configuration."""
        return (self._workdir / AGGREGATED_CONFIG_FILENAME).exists()

    def reset_baseline(self, existing_addresses: frozenset[str]) -> None:
        """Discard resources.tf so this run regenerates it from live data.

        Refused while the state tracks resources: their configuration
        cannot be regenerated (they are skipped from imports.tf, and
        terraform only generates config for import targets), so deleting
        the baseline would make the plan propose destroying all of them.
        """
        if existing_addresses:
            raise TerraformError(
                "--rebaseline cannot discard the configuration baseline while "
                f"the state file tracks {len(existing_addresses)} resource(s); "
                "their configuration would not be regenerated and the plan "
                "would propose destroying them. Reset or relocate the state "
                "file first."
            )
        aggregated = self._workdir / AGGREGATED_CONFIG_FILENAME
        if aggregated.exists():
            aggregated.unlink()
            logger.info(
                "Baseline reset: %s discarded; this run regenerates the "
                "configuration from currently discovered data.",
                AGGREGATED_CONFIG_FILENAME,
            )

    def plan_preview(self) -> TerraformCommandResult:
        """Read-only preview of what a disaster-recovery apply would do.

        Runs a plain ``terraform plan`` over the artifacts already in the
        workspace (no config generation) so the ``--rebuild`` action can
        show exactly what ``--confirm`` would execute.
        """
        return self._run(
            "plan",
            "-input=false",
            "-no-color",
            "-detailed-exitcode",
            allowed=(_PLAN_NO_CHANGES, _PLAN_CHANGES_PRESENT),
        )

    def rebuild_apply(self) -> TerraformCommandResult:
        """Execute ``terraform apply`` for an explicit disaster-recovery rebuild.

        The pipeline never calls this — normal runs are strictly
        read-only toward the Meraki organization. The only caller is the
        human-invoked ``--rebuild --confirm`` CLI action.
        """
        return self._run("apply", "-input=false", "-no-color", "-auto-approve")

    def _run(
        self, *args: str, allowed: tuple[int, ...] = (0,)
    ) -> TerraformCommandResult:
        command = (self._executable, *args)
        logger.debug("Executing: %s (cwd=%s)", " ".join(command), self._workdir)
        completed = subprocess.run(
            command,
            cwd=self._workdir,
            capture_output=True,
            text=True,
            check=False,
        )
        if completed.stdout:
            logger.debug("terraform %s stdout:\n%s", args[0], completed.stdout)
        if completed.stderr:
            logger.debug("terraform %s stderr:\n%s", args[0], completed.stderr)
        if completed.returncode not in allowed:
            raise TerraformError(
                f"terraform {args[0]} failed with exit code {completed.returncode}: "
                f"{completed.stderr.strip() or completed.stdout.strip()}"
            )
        return TerraformCommandResult(
            command=command,
            returncode=completed.returncode,
            stdout=completed.stdout,
            stderr=completed.stderr,
        )
