"""Local Terraform CLI runner built on the standard subprocess module.

Owns the execution workspace: writes the ``provider.tf`` anchor for the
``CiscoDevNet/meraki`` source with a local backend pinned to the state
file, runs ``init``, and executes the speculative generation plan
(``terraform plan -generate-config-out=...``).

Read-only guarantee: no run ever mutates the Meraki organization.
``terraform apply`` exists in exactly two shapes: (1)
:meth:`TerraformRunner.rebuild_apply`, reachable only through the
explicit, human-invoked ``--rebuild --confirm`` disaster-recovery
action, and (2) :meth:`TerraformRunner.apply_import_plan`, the
sync-mode state materializer. The latter is belt-and-suspenders
guarded *inside this module*: it runs a fresh saved plan, refuses
unless the summary verifies as import-only (0 to add, 0 to change,
0 to destroy), and then applies that exact plan file — ``import``
blocks only write local state and never touch Meraki, and no caller
can hand it a mutating plan.

State lifecycle: the state file location is explicit (``--state-file``,
defaulting to ``terraform.tfstate`` inside the workspace). An existing
file is reused so consecutive runs only import the delta; the runner
reports which resource addresses the state already tracks, so upstream
generation skips re-importing them.

Security: the Meraki token never touches disk — the provider block is
written credential-free. The ``CiscoDevNet/meraki`` Terraform provider
reads its credential from ``MERAKI_API_KEY``, so every terraform
subprocess is launched with that variable injected from meraki2tf's own
``MERAKI_DASHBOARD_API_KEY`` (an explicitly set ``MERAKI_API_KEY`` is
respected and never overridden).
"""

from __future__ import annotations

import json
import logging
import os
import re
import subprocess
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .config import API_KEY_ENV_VAR
from .fsperms import restrict_to_owner
from .plan_reconciler import (
    ReconciliationPlan,
    apply_remediations,
    classify_plan,
    drop_import_blocks,
    drop_resource_blocks,
    hcl_quote,
    validation_failures,
)

if TYPE_CHECKING:  # pragma: no cover - import cycle guard, types only
    from meraki2tf.provider_catalog import ProviderCatalog

logger = logging.getLogger(__name__)

#: Environment variable the ``CiscoDevNet/meraki`` Terraform provider
#: reads its credential from. Distinct from meraki2tf's own
#: ``MERAKI_DASHBOARD_API_KEY`` (the Meraki SDK convention), so the
#: runner bridges the two at subprocess launch.
PROVIDER_API_KEY_ENV_VAR = "MERAKI_API_KEY"

PROVIDER_FILENAME = "provider.tf"
GENERATED_CONFIG_FILENAME = "generated_resources.tf"
#: Persistent accumulated configuration: every plan's freshly generated
#: config is folded in here, so resources keep their HCL across runs.
AGGREGATED_CONFIG_FILENAME = "resources.tf"
#: The state must NOT be named ``terraform.tfstate`` inside the
#: workspace: ``terraform init`` treats a file of exactly that name
#: next to the configuration as pre-backend *legacy state* and
#: "migrates" it — emptying the file — whenever the backend cache is
#: absent or ``-reconfigure`` is used. Live-tested: that destroyed a
#: fully imported state on the second sync run.
DEFAULT_STATE_FILENAME = "meraki2tf.tfstate"
#: Terraform's legacy default state name; see DEFAULT_STATE_FILENAME.
LEGACY_STATE_FILENAME = "terraform.tfstate"
#: Saved plan file for the sync-mode guard: the plan verified as
#: import-only is the exact plan that gets applied.
SYNC_PLAN_FILENAME = "meraki2tf-sync.tfplan"

_PROVIDER_TF_TEMPLATE = """\
# Generated by meraki2tf — provider anchor for the execution workspace.
terraform {{
  backend "local" {{
    # State persists here across runs; point --state-file at an existing
    # state to keep aggregating into it instead of starting from zero.
    path = "{state_path}"
  }}

  required_providers {{
    meraki = {{
      source = "CiscoDevNet/meraki"
      # Resource identity schemas (the resource-matching ground truth)
      # ship from 1.12.0 onward.
      version = ">= 1.12.0"
    }}
  }}
}}

provider "meraki" {{
  # Credentials are never written to disk. The provider reads the
  # MERAKI_API_KEY environment variable; meraki2tf injects it into every
  # terraform subprocess from its own MERAKI_DASHBOARD_API_KEY. When
  # running terraform manually in this workspace, export MERAKI_API_KEY
  # (or set it from MERAKI_DASHBOARD_API_KEY) yourself.
}}
"""

#: ``terraform plan -detailed-exitcode`` contract.
_PLAN_NO_CHANGES = 0
_PLAN_ERROR = 1
_PLAN_CHANGES_PRESENT = 2

#: Terraform's human plan summary, e.g.
#: ``Plan: 875 to import, 0 to add, 2 to change, 0 to destroy.``
_PLAN_SUMMARY_RE = re.compile(
    r"Plan: (?:(?P<imports>\d+) to import, )?(?P<add>\d+) to add, "
    r"(?P<change>\d+) to change, (?P<destroy>\d+) to destroy"
)

#: Top-level resource block opener in terraform-generated configuration.
_RESOURCE_BLOCK_RE = re.compile(r'^resource\s+"(?P<type>[^"]+)"\s+"(?P<name>[^"]+)"\s*\{')


class TerraformError(RuntimeError):
    """A terraform invocation failed; message carries the CLI diagnostics."""


class TerraformNotFoundError(TerraformError):
    """The terraform executable could not be launched because it does not exist."""


class ImportGuardViolation(TerraformError):
    """The sync-mode guard refused to apply a plan that is not import-only.

    Raised *before* anything is applied. Carries the offending plan
    output so the orchestrator can abort with a drift alert instead of
    materializing a mutation.
    """

    def __init__(self, message: str, plan_output: str = "") -> None:
        super().__init__(message)
        self.plan_output = plan_output


#: HCL escaping lives with the reconciler's file surgery now; the alias
#: keeps this module's provider.tf templating (and its tests) intact.
_hcl_quote = hcl_quote


def _attr_pairs(
    kind: str, mapping: dict[str, tuple[str, ...]]
) -> set[tuple[str, str, str]]:
    """(kind, address, attribute) triples for progress comparison.

    Progress is tracked per attribute, not per address: a second
    reconciliation pass that touches a *new* attribute of an
    already-edited resource is progress; re-proposing an
    already-applied edit is not.
    """
    return {
        (kind, address, attr)
        for address, attrs in mapping.items()
        for attr in attrs
    }


def _merge_attr_map(
    into: dict[str, tuple[str, ...]], new: dict[str, tuple[str, ...]]
) -> None:
    """Merge attribute tuples per address (sorted, deduplicated)."""
    for address, attrs in new.items():
        into[address] = tuple(sorted({*into.get(address, ()), *attrs}))


@dataclass(frozen=True)
class PlanCounts:
    """Change counts parsed from a terraform plan summary line."""

    imports: int
    add: int
    change: int
    destroy: int

    @property
    def has_real_changes(self) -> bool:
        """True when the plan proposes mutations, not just imports."""
        return (self.add + self.change + self.destroy) > 0


@dataclass(frozen=True)
class TerraformCommandResult:
    """Captured outcome of one terraform subprocess invocation."""

    command: tuple[str, ...]
    returncode: int
    stdout: str
    stderr: str

    @property
    def has_changes(self) -> bool:
        """True for ``plan -detailed-exitcode`` runs that found a delta."""
        return self.returncode == _PLAN_CHANGES_PRESENT

    @property
    def plan_counts(self) -> PlanCounts | None:
        """Parsed plan summary counts, or None when no summary is present.

        Lets the orchestrator report exactly how much of the snapshot is
        still pending aggregation into state versus real change pressure.
        """
        match = _PLAN_SUMMARY_RE.search(self.stdout)
        if match is None:
            return None
        return PlanCounts(
            imports=int(match.group("imports") or 0),
            add=int(match.group("add")),
            change=int(match.group("change")),
            destroy=int(match.group("destroy")),
        )

    @property
    def has_drift(self) -> bool:
        """True when the plan proposes real changes (add/change/destroy).

        Pending ``import`` blocks are not drift — a plan that only
        imports means discovery found resources the state does not track
        yet, which is the tool's normal snapshot-growing behavior. Falls
        back to the ``-detailed-exitcode`` contract when no summary line
        can be parsed, so an unrecognized plan errs toward alerting.
        """
        counts = self.plan_counts
        if counts is None:
            return self.returncode == _PLAN_CHANGES_PRESENT
        return counts.has_real_changes


@dataclass(frozen=True)
class ReconciledPlanResult:
    """A generation plan plus everything reconciliation did to converge it.

    Exposes the same read surface as :class:`TerraformCommandResult`
    (``has_changes``/``has_drift``/``plan_counts``/``stdout``), so plan
    consumers are agnostic to whether reconciliation ran.
    """

    result: TerraformCommandResult
    #: Resources dropped from the kit because the provider's own
    #: validators reject the configuration terraform generated for
    #: them: address → operator-facing reason. These must be reported
    #: as unsupported (Cardinal Rule 2).
    dropped: dict[str, str]
    #: Secret attributes now excluded from management per resource —
    #: the DR kit cannot carry them; restore manually after a rebuild.
    ignored_secrets: dict[str, tuple[str, ...]]
    #: Attributes rewritten/injected to match state byte-for-byte.
    normalized: dict[str, tuple[str, ...]]

    @property
    def has_changes(self) -> bool:
        return self.result.has_changes

    @property
    def plan_counts(self) -> PlanCounts | None:
        return self.result.plan_counts

    @property
    def has_drift(self) -> bool:
        return self.result.has_drift

    @property
    def stdout(self) -> str:
        return self.result.stdout

    def merged_with_earlier(self, earlier: "ReconciledPlanResult") -> (
        "ReconciledPlanResult"
    ):
        """This plan's outcome, keeping remediations an earlier pass in
        the same run already applied (their diffs are suppressed now,
        so this pass alone would under-report them)."""
        return ReconciledPlanResult(
            result=self.result,
            dropped={**earlier.dropped, **self.dropped},
            ignored_secrets={**earlier.ignored_secrets, **self.ignored_secrets},
            normalized={**earlier.normalized, **self.normalized},
        )


class TerraformRunner:
    """Drives the local ``terraform`` binary inside a managed workspace."""

    def __init__(
        self,
        workdir: Path,
        executable: str = "terraform",
        state_path: Path | None = None,
    ) -> None:
        self._workdir = workdir
        self._executable = executable
        self._default_state = state_path is None
        self._state_path = (
            state_path if state_path is not None else workdir / DEFAULT_STATE_FILENAME
        ).resolve()
        if self._state_path == (workdir / LEGACY_STATE_FILENAME).resolve():
            raise TerraformError(
                f"--state-file must not be named {LEGACY_STATE_FILENAME} "
                "inside the workspace directory: terraform init treats "
                "that exact file as legacy state and empties it during "
                "backend initialization. Choose another name or location "
                f"(default: {DEFAULT_STATE_FILENAME} in the workdir)."
            )

    @property
    def workdir(self) -> Path:
        return self._workdir

    @property
    def state_path(self) -> Path:
        return self._state_path

    def prepare_workspace(self) -> Path:
        """Create the execution directory and anchor provider + state backend."""
        self._workdir.mkdir(parents=True, exist_ok=True)
        self._state_path.parent.mkdir(parents=True, exist_ok=True)
        self._adopt_legacy_state()
        provider_file = self._workdir / PROVIDER_FILENAME
        provider_file.write_text(
            _PROVIDER_TF_TEMPLATE.format(state_path=_hcl_quote(str(self._state_path))),
            encoding="utf-8",
        )
        if self._state_path.exists():
            self._restrict_state_permissions()
            logger.info("Reusing existing Terraform state at %s.", self._state_path)
        else:
            logger.info(
                "No Terraform state at %s; each run regenerates the full "
                "import snapshot (state is only written when you apply, "
                "e.g. via --rebuild --confirm).",
                self._state_path,
            )
        logger.debug("Workspace prepared at %s", self._workdir)
        return provider_file

    def _adopt_legacy_state(self) -> None:
        """Rescue state from the old default location.

        Earlier meraki2tf versions kept the state at
        ``<workdir>/terraform.tfstate`` — the exact filename terraform's
        legacy-state migration destroys (see DEFAULT_STATE_FILENAME).
        When the current default location is empty and the legacy file
        holds a non-empty state, move it so accumulated imports survive
        the upgrade.
        """
        if not self._default_state:
            return
        legacy = self._workdir / LEGACY_STATE_FILENAME
        if (
            legacy.exists()
            and legacy.stat().st_size > 0
            and not self._state_path.exists()
        ):
            legacy.rename(self._state_path)
            logger.info(
                "Adopted legacy state file %s as %s (terraform init "
                "would destroy state stored under the legacy name).",
                legacy,
                self._state_path,
            )

    def existing_addresses(self) -> frozenset[str]:
        """Resource addresses (``type.name``) already tracked in the state.

        Lets generation skip re-importing resources from prior runs so
        consecutive executions only aggregate the delta.
        """
        if not self._state_path.exists():
            return frozenset()
        try:
            document = json.loads(self._state_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise TerraformError(
                f"Existing state file {self._state_path} is unreadable: {exc}"
            ) from exc
        resources = document.get("resources", []) if isinstance(document, dict) else []
        addresses = frozenset(
            f"{resource['type']}.{resource['name']}"
            for resource in resources
            if isinstance(resource, dict)
            and resource.get("mode") == "managed"
            and resource.get("type")
            and resource.get("name")
        )
        logger.info(
            "Existing state tracks %d managed resource(s).", len(addresses)
        )
        return addresses

    def init(self) -> TerraformCommandResult:
        # -reconfigure keeps init idempotent when the backend/state path
        # differs from a previous run in the same workspace.
        return self._run("init", "-input=false", "-no-color", "-reconfigure")

    def provider_schema_catalog(self) -> "ProviderCatalog":
        """Identity-schema catalog of the provider terraform installed.

        Requires an initialized workspace (:meth:`init`). This is the
        authoritative source for resource matching: the catalog always
        reflects the provider version terraform actually selected.
        """
        from meraki2tf.provider_catalog import ProviderCatalog

        result = self._run("providers", "schema", "-json")
        try:
            document = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise TerraformError(
                f"terraform providers schema produced unparseable output: {exc}"
            ) from exc
        if not isinstance(document, dict):
            raise TerraformError(
                "terraform providers schema produced a non-object document."
            )
        return ProviderCatalog.from_schema_document(document)

    #: Plan invocations one generation call may spend converging: one
    #: for validation drops, one for change remediation, one to verify.
    #: Runaway backstop for the reconciliation loop. Every iteration
    #: must make progress (drop a rejected resource or apply a new
    #: remediation) or the loop breaks on its own; the cap only guards
    #: against pathological plan behavior. Real runs need up to ~4
    #: passes: terraform reports validation errors piecemeal, so two
    #: drop rounds can precede the classify + verify rounds.
    _MAX_PLAN_ATTEMPTS = 10

    def plan_with_generation(
        self, save_plan: bool = False, reconcile: bool = True
    ) -> ReconciledPlanResult:
        """Speculative check: plan imports, generate missing config, and
        reconcile provider round-trip artifacts (see plan_reconciler).

        Returns with ``has_changes`` reflecting the ``-detailed-exitcode``
        contract (0 = state in sync, 2 = delta present). The plan is
        always saved to the sync plan file (reconciliation classifies it
        via ``show -json``; sync mode re-verifies its own fresh plan
        before applying regardless). Bounded loop: at most
        ``_MAX_PLAN_ATTEMPTS`` plan invocations — remaining changes after
        that are reported as drift, never looped on.
        """
        dropped: dict[str, str] = {}
        ignored: dict[str, tuple[str, ...]] = {}
        normalized: dict[str, tuple[str, ...]] = {}
        args = (
            "plan",
            "-input=false",
            "-no-color",
            "-detailed-exitcode",
            f"-generate-config-out={GENERATED_CONFIG_FILENAME}",
            f"-out={SYNC_PLAN_FILENAME}",
        )
        allowed = (
            (_PLAN_NO_CHANGES, _PLAN_ERROR, _PLAN_CHANGES_PRESENT)
            if reconcile
            else (_PLAN_NO_CHANGES, _PLAN_CHANGES_PRESENT)
        )
        attempt = 0
        while True:
            attempt += 1
            # terraform refuses to overwrite an existing generation
            # target; leftovers (interrupted or prior iteration) are
            # absorbed first so surgery always edits resources.tf.
            self._absorb_generated_config()
            result = self._run(*args, allowed=allowed)
            self._absorb_generated_config()
            final_attempt = attempt >= self._MAX_PLAN_ATTEMPTS
            if result.returncode == _PLAN_ERROR:
                failures = validation_failures(
                    result.stderr or result.stdout
                )
                if not failures or final_attempt:
                    raise TerraformError(
                        f"terraform plan failed with exit code "
                        f"{result.returncode}: "
                        f"{result.stderr.strip() or result.stdout.strip()}"
                    )
                self._drop_unexpressible(failures)
                dropped.update(failures)
                continue
            if not reconcile or not result.has_drift or final_attempt:
                # import-only plans are healthy snapshot growth; only
                # real add/change/destroy pressure warrants classifying.
                break
            reconciliation = classify_plan(self._show_plan_document())
            if not reconciliation.has_remediations:
                break
            new_ignored, new_normalized = apply_remediations(
                self._workdir,
                reconciliation,
                (GENERATED_CONFIG_FILENAME, AGGREGATED_CONFIG_FILENAME),
            )
            proposed = _attr_pairs("ignore", new_ignored) | _attr_pairs(
                "normalize", new_normalized
            )
            applied = _attr_pairs("ignore", ignored) | _attr_pairs(
                "normalize", normalized
            )
            if not proposed - applied:
                # Every proposed (address, attribute) remediation was
                # applied before yet the diff persists — re-editing
                # would loop forever, so surface it as drift instead.
                logger.warning(
                    "Reconciliation made no further progress; reporting "
                    "the remaining plan changes as drift."
                )
                break
            _merge_attr_map(ignored, new_ignored)
            _merge_attr_map(normalized, new_normalized)
            self._log_reconciliation(reconciliation, new_ignored, new_normalized)
        return ReconciledPlanResult(
            result=result,
            dropped=dropped,
            ignored_secrets=ignored,
            normalized=normalized,
        )

    def _drop_unexpressible(self, failures: dict[str, str]) -> None:
        """Remove kit artifacts for resources the provider rejects.

        The provider's validators refused the configuration generated
        from its own Read (e.g. enum case the API does not emit) — the
        resource cannot round-trip, so it leaves the kit and is
        reported as unsupported by the orchestrator.
        """
        addresses = set(failures)
        logger.warning(
            "Dropping %d resource(s) whose generated configuration the "
            "provider itself rejects: %s",
            len(addresses), ", ".join(sorted(addresses)),
        )
        drop_resource_blocks(
            (
                self._workdir / GENERATED_CONFIG_FILENAME,
                self._workdir / AGGREGATED_CONFIG_FILENAME,
            ),
            addresses,
        )
        from meraki2tf.hcl_generator import IMPORTS_FILENAME

        drop_import_blocks(self._workdir / IMPORTS_FILENAME, addresses)

    @staticmethod
    def _log_reconciliation(
        plan: ReconciliationPlan,
        ignored: dict[str, tuple[str, ...]],
        normalized: dict[str, tuple[str, ...]],
    ) -> None:
        logger.info(
            "Plan reconciliation: %d secret attribute set(s) marked "
            "unmanaged, %d resource(s) normalized to state values%s.",
            len(ignored),
            len(normalized),
            (
                f"; {len(plan.real_changes)} real change(s) left as drift"
                if plan.real_changes
                else ""
            ),
        )

    def plan_resource_actions(self) -> dict[str, tuple[str, ...]]:
        """Per-resource actions from the saved sync plan (``show -json``).

        Maps each planned resource address to its action tuple (e.g.
        ``("update",)`` or ``("no-op",)``), letting sync mode separate
        modified objects (Meraki is truth → baseline regeneration) from
        anything else (abort and alert).
        """
        document = self._show_plan_document()
        actions: dict[str, tuple[str, ...]] = {}
        changes = document.get("resource_changes") if isinstance(document, dict) else None
        for change in changes or ():
            if not isinstance(change, dict) or not change.get("address"):
                continue
            change_body = change.get("change")
            raw = change_body.get("actions", ()) if isinstance(change_body, dict) else ()
            actions[str(change["address"])] = tuple(str(action) for action in raw)
        return actions

    def _show_plan_document(self) -> Any:
        """The saved sync plan rendered as a JSON document.

        Consumers guard the document shape themselves (an unexpected
        non-object tolerantly classifies as "nothing to act on").
        """
        result = self._run("show", "-json", SYNC_PLAN_FILENAME)
        try:
            return json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise TerraformError(
                f"terraform show -json produced unparseable output: {exc}"
            ) from exc

    def apply_import_plan(self) -> tuple[str, ...]:
        """Guarded sync-mode apply: grow the state, never touch Meraki.

        Belt-and-suspenders contract enforcement — regardless of what
        the caller believes about the plan, this method re-verifies
        immediately before applying: it saves a fresh plan, refuses with
        :class:`ImportGuardViolation` unless the summary parses as
        import-only (0 to add, 0 to change, 0 to destroy — an
        unparseable summary also refuses), and then applies that exact
        saved plan file, so nothing can change between verification and
        execution. Returns the resource addresses the apply added to
        the state, sorted, so every run reports exactly how the state
        grew.
        """
        before = self.existing_addresses()
        plan_file = self._workdir / SYNC_PLAN_FILENAME
        try:
            result = self._run(
                "plan",
                "-input=false",
                "-no-color",
                "-detailed-exitcode",
                f"-out={SYNC_PLAN_FILENAME}",
                allowed=(_PLAN_NO_CHANGES, _PLAN_CHANGES_PRESENT),
            )
            if result.returncode == _PLAN_NO_CHANGES:
                logger.info("State already aggregates every import; nothing to apply.")
                return ()
            counts = result.plan_counts
            if counts is None:
                raise ImportGuardViolation(
                    "Refusing to apply: the plan summary could not be parsed, so "
                    "it cannot be verified as import-only.",
                    plan_output=result.stdout,
                )
            if counts.has_real_changes:
                raise ImportGuardViolation(
                    "Refusing to apply: the plan proposes mutations "
                    f"({counts.add} to add, {counts.change} to change, "
                    f"{counts.destroy} to destroy); only 100% import plans may "
                    "be applied unattended.",
                    plan_output=result.stdout,
                )
            logger.info(
                "Import-only plan verified (%d import(s), 0 to add, 0 to "
                "change, 0 to destroy); applying to materialize state.",
                counts.imports,
            )
            self._run("apply", "-input=false", "-no-color", SYNC_PLAN_FILENAME)
            self._restrict_state_permissions()
        finally:
            plan_file.unlink(missing_ok=True)
        added = tuple(sorted(self.existing_addresses() - before))
        logger.info("State materialized: %d resource(s) added.", len(added))
        return added

    def remove_resources(self, addresses: Iterable[str]) -> None:
        """Remove resources from the accumulated baseline and the state.

        Local surgery only — Meraki is never touched. Used for the two
        human-sanctioned removal paths: confirmed deletions (the object
        is gone from Meraki) and sync-mode baseline regeneration of
        modified objects (state rm + prune turns them back into import
        candidates, so terraform regenerates their HCL from current
        Meraki truth).
        """
        targets = sorted(set(addresses))
        if not targets:
            return
        self._prune_baseline(targets)
        tracked = [address for address in targets if address in self.existing_addresses()]
        if tracked:
            self._run("state", "rm", "-no-color", *tracked)
            logger.info("Removed %d resource(s) from the Terraform state.", len(tracked))

    def _prune_baseline(self, addresses: Iterable[str]) -> None:
        """Drop the given resources' blocks from the accumulated resources.tf.

        The baseline is terraform-generated (hclfmt formatted), so every
        top-level resource block opens with ``resource "type" "name" {``
        at column 0 and closes with ``}`` at column 0.
        """
        aggregated = self._workdir / AGGREGATED_CONFIG_FILENAME
        if not aggregated.exists():
            return
        remove = set(addresses)
        lines = aggregated.read_text(encoding="utf-8").splitlines(keepends=True)
        kept: list[str] = []
        pruned = 0
        index = 0
        while index < len(lines):
            match = _RESOURCE_BLOCK_RE.match(lines[index])
            if match and f"{match['type']}.{match['name']}" in remove:
                pruned += 1
                if not lines[index].rstrip().endswith("{"):  # one-line block
                    index += 1
                else:
                    index += 1
                    while index < len(lines) and not lines[index].startswith("}"):
                        index += 1
                    index += 1  # the closing brace itself
                while index < len(lines) and not lines[index].strip():
                    index += 1  # the blank separator after the block
                continue
            kept.append(lines[index])
            index += 1
        if pruned:
            aggregated.write_text("".join(kept), encoding="utf-8")
            logger.info(
                "Pruned %d resource block(s) from %s.", pruned, AGGREGATED_CONFIG_FILENAME
            )

    def _absorb_generated_config(self) -> None:
        """Fold freshly generated config into the persistent resources.tf.

        Deleting the generation target instead (the naive fix for
        terraform's refusal to overwrite it) would leave state-tracked
        resources with no configuration, so every subsequent plan would
        propose destroying them — a false drift alert, and a workspace
        that tears the organization down if rebuild-applied. Accumulating
        keeps the workspace a faithful, apply-safe DR kit and lets the
        plan compare tracked resources against their captured baseline.
        """
        generated = self._workdir / GENERATED_CONFIG_FILENAME
        if not generated.exists():
            return
        content = generated.read_text(encoding="utf-8")
        if content.strip():
            aggregated = self._workdir / AGGREGATED_CONFIG_FILENAME
            with aggregated.open("a", encoding="utf-8") as handle:
                handle.write(content if content.endswith("\n") else content + "\n")
            logger.info(
                "Absorbed newly generated configuration into %s.",
                AGGREGATED_CONFIG_FILENAME,
            )
        generated.unlink()

    def has_config_baseline(self) -> bool:
        """Whether the workspace holds accumulated resource configuration."""
        return (self._workdir / AGGREGATED_CONFIG_FILENAME).exists()

    def reset_baseline(self, existing_addresses: frozenset[str]) -> None:
        """Discard resources.tf so this run regenerates it from live data.

        Refused while the state tracks resources: their configuration
        cannot be regenerated (they are skipped from imports.tf, and
        terraform only generates config for import targets), so deleting
        the baseline would make the plan propose destroying all of them.
        """
        if existing_addresses:
            raise TerraformError(
                "--rebaseline cannot discard the configuration baseline while "
                f"the state file tracks {len(existing_addresses)} resource(s); "
                "their configuration would not be regenerated and the plan "
                "would propose destroying them. Reset or relocate the state "
                "file first."
            )
        aggregated = self._workdir / AGGREGATED_CONFIG_FILENAME
        if aggregated.exists():
            aggregated.unlink()
            logger.info(
                "Baseline reset: %s discarded; this run regenerates the "
                "configuration from currently discovered data.",
                AGGREGATED_CONFIG_FILENAME,
            )

    def plan_preview(self) -> TerraformCommandResult:
        """Read-only preview of what a disaster-recovery apply would do.

        Runs a plain ``terraform plan`` over the artifacts already in the
        workspace (no config generation) so the ``--rebuild`` action can
        show exactly what ``--confirm`` would execute.
        """
        return self._run(
            "plan",
            "-input=false",
            "-no-color",
            "-detailed-exitcode",
            allowed=(_PLAN_NO_CHANGES, _PLAN_CHANGES_PRESENT),
        )

    def rebuild_apply(self) -> TerraformCommandResult:
        """Execute ``terraform apply`` for an explicit disaster-recovery rebuild.

        The pipeline never calls this — normal runs are strictly
        read-only toward the Meraki organization. The only caller is the
        human-invoked ``--rebuild --confirm`` CLI action.
        """
        result = self._run("apply", "-input=false", "-no-color", "-auto-approve")
        self._restrict_state_permissions()
        return result

    def _restrict_state_permissions(self) -> None:
        """Owner-only (0600) permissions on the state file and its backup.

        Terraform state stores every sensitive attribute in plaintext
        (SSID PSKs, SNMP community strings, …); terraform itself writes
        it with default permissions.
        """
        for path in (
            self._state_path,
            self._state_path.with_name(self._state_path.name + ".backup"),
        ):
            if path.exists():
                restrict_to_owner(path)

    @staticmethod
    def _subprocess_env() -> dict[str, str]:
        """Environment for terraform subprocesses.

        The ``CiscoDevNet/meraki`` provider authenticates via
        ``MERAKI_API_KEY``, while meraki2tf follows the Meraki SDK
        convention of ``MERAKI_DASHBOARD_API_KEY``. Bridge the two so
        the speculative plan and guarded applies can authenticate,
        keeping the credential out of every file the runner writes. An
        explicitly set ``MERAKI_API_KEY`` always wins.
        """
        env = dict(os.environ)
        dashboard_key = env.get(API_KEY_ENV_VAR, "").strip()
        if dashboard_key and not env.get(PROVIDER_API_KEY_ENV_VAR, "").strip():
            env[PROVIDER_API_KEY_ENV_VAR] = dashboard_key
        return env

    def _run(
        self, *args: str, allowed: tuple[int, ...] = (0,)
    ) -> TerraformCommandResult:
        command = (self._executable, *args)
        logger.debug("Executing: %s (cwd=%s)", " ".join(command), self._workdir)
        try:
            completed = subprocess.run(
                command,
                cwd=self._workdir,
                capture_output=True,
                text=True,
                check=False,
                env=self._subprocess_env(),
            )
        except FileNotFoundError as exc:
            raise TerraformNotFoundError(
                f"terraform executable {self._executable!r} was not found. "
                "Install Terraform (https://developer.hashicorp.com/terraform/install) "
                "and ensure it is on PATH, or pass --terraform-bin with the full "
                "path to the binary."
            ) from exc
        if completed.stdout:
            if "-json" in args:
                # Machine-readable output (plan/state JSON) carries
                # sensitive values in plaintext — never log the body.
                # Human-readable terraform output masks them itself.
                logger.debug(
                    "terraform %s stdout: %d byte(s) of machine-readable "
                    "JSON (body not logged: may carry sensitive values).",
                    args[0], len(completed.stdout),
                )
            else:
                logger.debug(
                    "terraform %s stdout:\n%s", args[0], completed.stdout
                )
        if completed.stderr:
            logger.debug("terraform %s stderr:\n%s", args[0], completed.stderr)
        if completed.returncode not in allowed:
            raise TerraformError(
                f"terraform {args[0]} failed with exit code {completed.returncode}: "
                f"{completed.stderr.strip() or completed.stdout.strip()}"
            )
        return TerraformCommandResult(
            command=command,
            returncode=completed.returncode,
            stdout=completed.stdout,
            stderr=completed.stderr,
        )
